"""Approval domain — system decision logic and approval service.

Owner: approval-service (in monolith: approval_domain module).

This module contains:
  - system_decide(): pure function that decides publish_status from quality report
    and agent review. Callable from the pipeline without DB access.
  - ApprovalService: class that manages approval tickets, audit logs, and
    final_doc_id generation. Requires a DB session.

Rules:
  - system_decide does NOT write documents, policies, or index state.
  - ApprovalService writes approval_tickets and approval_audit_log only.
  - ApprovalService does NOT write documents, policies, or index state.
  - final_doc_id is only generated by ApprovalService on approve / system_approve.
  - REJECTED tickets never have a final_doc_id.
"""

from __future__ import annotations

import hashlib
import secrets
from datetime import datetime, timezone
from typing import TYPE_CHECKING

from reality_rag_contracts import (
    AgentReview,
    ApprovalAction,
    ApprovalAuditLog,
    ApprovalTicket,
    ApprovalTicketState,
    EventType,
    PublishStatus,
    QualityReport,
    ReviewDecision,
    VersionDecision,
)
from reality_rag_persistence import EventPublisher
from .review_artifacts import build_ticket_event_payload

if TYPE_CHECKING:
    from sqlalchemy.orm import Session


def system_decide(
    quality_report: QualityReport | None,
    agent_review: AgentReview | None,
) -> PublishStatus:
    """Resolve publish_status from quality report and agent review.

    This is the system auto-approve path decision engine.  It is a pure
    function with no side effects.  In phase 5 it is wrapped by
    ApprovalService which also creates tickets and audit logs.
    """
    if agent_review is None:
        return (
            quality_report.recommended_review_status
            if quality_report is not None
            else PublishStatus.PENDING_REVIEW
        )

    decision = (
        agent_review.decision
        if isinstance(agent_review.decision, ReviewDecision)
        or agent_review.decision is None
        else ReviewDecision(agent_review.decision)
    )
    recommendation = (
        agent_review.publish_recommendation
        if isinstance(agent_review.publish_recommendation, PublishStatus)
        or agent_review.publish_recommendation is None
        else PublishStatus(agent_review.publish_recommendation)
    )

    if decision == ReviewDecision.REJECT:
        return PublishStatus.REJECTED
    if decision == ReviewDecision.QUARANTINE:
        return PublishStatus.QUARANTINED
    if decision == ReviewDecision.REQUEST_CHANGES:
        return PublishStatus.PENDING_REVIEW
    # Governance guardrail: privacy / access-control style policies and
    # high-authority docs should wait for manual approval even if the LLM
    # returns approve. This makes the pending path deterministic in real runs.
    if agent_review is not None:
        document_type_raw = getattr(agent_review, "document_type", "") or ""
        document_type = document_type_raw.strip().lower() if isinstance(document_type_raw, str) else ""
        authority_level = getattr(agent_review, "suggested_authority_level", 0)
        authority_level = authority_level if isinstance(authority_level, int) else 0
        risk_tags = getattr(agent_review, "risk_tags", []) or []
        risk_tags = risk_tags if isinstance(risk_tags, list) else []
        if (
            "privacy" in document_type
            or "access" in document_type
            or authority_level >= 7
            or any(isinstance(tag, str) and "privacy" in tag.lower() for tag in risk_tags)
        ):
            return PublishStatus.PENDING_REVIEW
    if recommendation is not None:
        return recommendation
    return (
        quality_report.recommended_review_status
        if quality_report is not None
        else PublishStatus.PENDING_REVIEW
    )


class ApprovalService:
    """Approval service — manages tickets, audit logs, and final_doc_id generation.

    Owner: approval-service (in monolith: approval_domain module).
    """

    def __init__(self, session: Session) -> None:
        from reality_rag_persistence.repositories.approval_tickets import (
            ApprovalTicketRepository,
        )
        from reality_rag_persistence.repositories.approval_audit_log import (
            ApprovalAuditLogRepository,
        )

        self._session = session
        self._ticket_repo = ApprovalTicketRepository(session)
        self._audit_repo = ApprovalAuditLogRepository(session)
        self._event_publisher = EventPublisher(session)

    # ------------------------------------------------------------------
    # System auto-approve / auto-reject
    # ------------------------------------------------------------------

    def submit_auto_approve(
        self,
        *,
        intake_job_id: str,
        preliminary_doc_id: str,
        collection_id: str,
        logical_document_id: str,
        version: int,
        confirmed_tags: list[str] | None = None,
        version_conflict: dict | None = None,
    ) -> ApprovalTicket:
        """Create a SYSTEM_DECIDED ticket for auto-approve and generate final_doc_id."""
        ticket_id = _generate_ticket_id()
        final_doc_id = self._generate_final_doc_id(
            preliminary_doc_id=preliminary_doc_id,
            logical_document_id=logical_document_id,
            version=version,
            version_decision=None,
        )

        ticket = ApprovalTicket(
            ticket_id=ticket_id,
            intake_job_id=intake_job_id,
            approval_round=1,
            preliminary_doc_id=preliminary_doc_id,
            collection_id=collection_id,
            state=ApprovalTicketState.SYSTEM_DECIDED,
            routing_recommendation="auto_approve",
            decision="approve",
            decision_actor="system",
            decision_reason="满足自动入库策略",
            final_doc_id=final_doc_id,
            confirmed_tags=confirmed_tags or [],
            created_at=datetime.now(timezone.utc),
        )
        created_ticket = self._ticket_repo.create(ticket)

        self._append_audit(
            ticket=created_ticket,
            action=ApprovalAction.SYSTEM_APPROVE,
            before_state=None,
            after_state=ApprovalTicketState.SYSTEM_DECIDED.value,
            reason="满足自动入库策略",
        )
        self._publish_decided_event(
            created_ticket,
            auto_approved=True,
            manual_override=False,
            ticket_event_version=1,
        )
        return created_ticket

    def submit_auto_reject(
        self,
        *,
        intake_job_id: str,
        preliminary_doc_id: str,
        collection_id: str,
        rejection_reason: str,
    ) -> ApprovalTicket:
        """Create a SYSTEM_DECIDED ticket for auto-reject. No final_doc_id."""
        ticket_id = _generate_ticket_id()

        ticket = ApprovalTicket(
            ticket_id=ticket_id,
            intake_job_id=intake_job_id,
            approval_round=1,
            preliminary_doc_id=preliminary_doc_id,
            collection_id=collection_id,
            state=ApprovalTicketState.SYSTEM_DECIDED,
            routing_recommendation="auto_approve",
            decision="reject",
            decision_actor="system",
            decision_reason=rejection_reason,
            created_at=datetime.now(timezone.utc),
        )
        created_ticket = self._ticket_repo.create(ticket)

        self._append_audit(
            ticket=created_ticket,
            action=ApprovalAction.SYSTEM_REJECT,
            before_state=None,
            after_state=ApprovalTicketState.SYSTEM_DECIDED.value,
            reason=rejection_reason,
        )
        self._publish_decided_event(
            created_ticket,
            auto_approved=True,
            manual_override=False,
            ticket_event_version=1,
            extra={"reason": rejection_reason},
        )
        return created_ticket

    # ------------------------------------------------------------------
    # Manual approval lifecycle
    # ------------------------------------------------------------------

    def create_pending(
        self,
        *,
        intake_job_id: str,
        preliminary_doc_id: str,
        collection_id: str,
        routing_recommendation: str = "require_approval",
    ) -> ApprovalTicket:
        """Create a PENDING ticket for manual approval."""
        ticket_id = _generate_ticket_id()

        ticket = ApprovalTicket(
            ticket_id=ticket_id,
            intake_job_id=intake_job_id,
            approval_round=1,
            preliminary_doc_id=preliminary_doc_id,
            collection_id=collection_id,
            state=ApprovalTicketState.PENDING,
            routing_recommendation=routing_recommendation,
            created_at=datetime.now(timezone.utc),
        )
        created = self._ticket_repo.create(ticket)
        self._publish_pending_event(created)
        return created

    def approve(
        self,
        *,
        ticket_id: str,
        actor_id: str,
        confirmed_tags: list[str] | None = None,
        version_decision: VersionDecision | None = None,
        supersedes_final_doc_id: str | None = None,
    ) -> ApprovalTicket:
        """Approve a PENDING ticket. Generates final_doc_id if not present."""
        ticket = self._ticket_repo.get(ticket_id)
        if ticket is None:
            raise ValueError(f"Ticket not found: {ticket_id}")
        if ticket.state != ApprovalTicketState.PENDING:
            raise ValueError(f"Ticket {ticket_id} is not in PENDING state")

        final_doc_id = ticket.final_doc_id
        if final_doc_id is None:
            final_doc_id = self._generate_final_doc_id(
                preliminary_doc_id=ticket.preliminary_doc_id,
                logical_document_id="",
                version=1,
                version_decision=version_decision,
            )

        updated = self._ticket_repo.update_state(
            ticket_id=ticket_id,
            new_state=ApprovalTicketState.APPROVED,
            decision="approve",
            decision_actor=actor_id,
            final_doc_id=final_doc_id,
            confirmed_tags=confirmed_tags or [],
            version_decision=version_decision.value if version_decision else None,
            supersedes_final_doc_id=supersedes_final_doc_id,
        )

        self._append_audit(
            ticket=updated,
            action=ApprovalAction.APPROVE,
            before_state=ApprovalTicketState.PENDING.value,
            after_state=ApprovalTicketState.APPROVED.value,
            reason=None,
        )
        self._publish_decided_event(
            updated,
            auto_approved=False,
            manual_override=True,
            ticket_event_version=2,
        )
        return updated

    def reject(
        self,
        *,
        ticket_id: str,
        actor_id: str,
        rejection_reason: str,
    ) -> ApprovalTicket:
        """Reject a PENDING ticket. Does NOT generate final_doc_id."""
        ticket = self._ticket_repo.get(ticket_id)
        if ticket is None:
            raise ValueError(f"Ticket not found: {ticket_id}")
        if ticket.state != ApprovalTicketState.PENDING:
            raise ValueError(f"Ticket {ticket_id} is not in PENDING state")

        updated = self._ticket_repo.update_state(
            ticket_id=ticket_id,
            new_state=ApprovalTicketState.REJECTED,
            decision="reject",
            decision_actor=actor_id,
            decision_reason=rejection_reason,
        )

        self._append_audit(
            ticket=updated,
            action=ApprovalAction.REJECT,
            before_state=ApprovalTicketState.PENDING.value,
            after_state=ApprovalTicketState.REJECTED.value,
            reason=rejection_reason,
        )
        self._publish_decided_event(
            updated,
            auto_approved=False,
            manual_override=True,
            ticket_event_version=2,
            extra={"reason": rejection_reason},
        )
        return updated

    def return_to_stage(
        self,
        *,
        ticket_id: str,
        actor_id: str,
        return_target_stage: str,
        return_reason: str,
    ) -> tuple[ApprovalTicket, ApprovalTicket]:
        """Return a PENDING ticket to a previous stage.

        Marks current ticket as RETURNED and creates a new PENDING ticket
        with incremented approval_round.
        """
        ticket = self._ticket_repo.get(ticket_id)
        if ticket is None:
            raise ValueError(f"Ticket not found: {ticket_id}")
        if ticket.state != ApprovalTicketState.PENDING:
            raise ValueError(f"Ticket {ticket_id} is not in PENDING state")

        updated = self._ticket_repo.update_state(
            ticket_id=ticket_id,
            new_state=ApprovalTicketState.RETURNED,
            decision="return",
            decision_actor=actor_id,
            return_target_stage=return_target_stage,
            return_reason=return_reason,
        )

        self._append_audit(
            ticket=updated,
            action=ApprovalAction.RETURN,
            before_state=ApprovalTicketState.PENDING.value,
            after_state=ApprovalTicketState.RETURNED.value,
            reason=return_reason,
        )

        new_ticket_id = _generate_ticket_id()
        new_ticket = ApprovalTicket(
            ticket_id=new_ticket_id,
            intake_job_id=ticket.intake_job_id,
            approval_round=ticket.approval_round + 1,
            preliminary_doc_id=ticket.preliminary_doc_id,
            collection_id=ticket.collection_id,
            state=ApprovalTicketState.PENDING,
            routing_recommendation=ticket.routing_recommendation,
            created_at=datetime.now(timezone.utc),
        )
        created_new = self._ticket_repo.create(new_ticket)
        self._publish_decided_event(
            updated,
            auto_approved=False,
            manual_override=True,
            ticket_event_version=2,
            extra={
                "return_target_stage": return_target_stage,
                "return_reason": return_reason,
                "new_ticket_id": created_new.ticket_id,
            },
        )
        self._publish_pending_event(created_new)
        return updated, created_new

    def expire(
        self,
        *,
        ticket_id: str,
    ) -> ApprovalTicket:
        """Expire a PENDING ticket."""
        ticket = self._ticket_repo.get(ticket_id)
        if ticket is None:
            raise ValueError(f"Ticket not found: {ticket_id}")
        if ticket.state != ApprovalTicketState.PENDING:
            raise ValueError(f"Ticket {ticket_id} is not in PENDING state")

        updated = self._ticket_repo.update_state(
            ticket_id=ticket_id,
            new_state=ApprovalTicketState.EXPIRED,
            decision="expire",
            decision_actor="system",
        )

        self._append_audit(
            ticket=updated,
            action=ApprovalAction.EXPIRE,
            before_state=ApprovalTicketState.PENDING.value,
            after_state=ApprovalTicketState.EXPIRED.value,
            reason="????",
        )
        self._publish_decided_event(
            updated,
            auto_approved=False,
            manual_override=False,
            ticket_event_version=2,
        )
        return updated

    def get_ticket_history(self, intake_job_id: str) -> list[ApprovalTicket]:
        """Return all tickets for an intake job, ordered by created_at."""
        return self._ticket_repo.get_by_intake_job(intake_job_id)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _generate_final_doc_id(
        self,
        *,
        preliminary_doc_id: str,
        logical_document_id: str,
        version: int,
        version_decision: VersionDecision | None = None,
    ) -> str:
        """Generate final_doc_id based on preliminary_doc_id and version decision.

        Rules:
          - No version_conflict: final_doc_id = preliminary_doc_id
          - new_version: final_doc_id = preliminary_doc_id (version already in doc_id)
          - independent_document: append extra digest to make unique
          - business_duplicate: caller handles reject, no final_doc_id needed
        """
        if version_decision == VersionDecision.BUSINESS_DUPLICATE:
            raise ValueError("business_duplicate does not generate final_doc_id")

        if version_decision == VersionDecision.INDEPENDENT_DOCUMENT:
            digest = secrets.token_hex(4)
            base = preliminary_doc_id.rsplit("-v", 1)[0]
            return f"{base}-{digest}-v1"

        return preliminary_doc_id

    def _append_audit(
        self,
        *,
        ticket: ApprovalTicket,
        action: ApprovalAction,
        before_state: str | None,
        after_state: str | None,
        reason: str | None,
    ) -> ApprovalAuditLog:
        """Append an audit log entry."""
        audit_id = _generate_audit_id()
        payload_hash = _hash_payload(
            f"{ticket.ticket_id}:{action.value}:{before_state}:{after_state}:{reason or ''}"
        )
        return self._audit_repo.append(
            audit_id=audit_id,
            ticket_id=ticket.ticket_id,
            intake_job_id=ticket.intake_job_id,
            actor_id=ticket.decision_actor or "system",
            action=action,
            before_state=before_state,
            after_state=after_state,
            reason=reason,
            payload_hash=payload_hash,
        )

    def _publish_pending_event(self, ticket: ApprovalTicket) -> None:
        payload = self._base_ticket_event_payload(ticket)
        payload.update({
            "approval_round": ticket.approval_round,
            "expires_at": ticket.expires_at.isoformat() if ticket.expires_at else None,
            "ticket_event_version": 1,
        })
        self._event_publisher.publish(
            event_type=EventType.APPROVAL_PENDING,
            aggregate_type="intake_job",
            aggregate_id=ticket.intake_job_id,
            payload=payload,
            idempotency_key=f"{ticket.intake_job_id}:approval_pending:{ticket.ticket_id}",
        )

    def _publish_decided_event(
        self,
        ticket: ApprovalTicket,
        *,
        auto_approved: bool,
        manual_override: bool,
        ticket_event_version: int,
        extra: dict[str, object] | None = None,
    ) -> None:
        payload = self._base_ticket_event_payload(ticket)
        payload.update({
            "auto_approved": auto_approved,
            "manual_override": manual_override,
            "ticket_event_version": ticket_event_version,
        })
        if extra:
            payload.update(extra)
        self._event_publisher.publish(
            event_type=EventType.APPROVAL_DECIDED,
            aggregate_type="intake_job",
            aggregate_id=ticket.intake_job_id,
            payload=payload,
            idempotency_key=f"{ticket.intake_job_id}:approval_decided:{ticket.ticket_id}",
        )

    def _base_ticket_event_payload(self, ticket: ApprovalTicket) -> dict[str, object]:
        payload = build_ticket_event_payload(self._session, ticket)
        payload.update({
            "intake_job_id": ticket.intake_job_id,
            "ticket_id": ticket.ticket_id,
            "approval_round": ticket.approval_round,
            "state": ticket.state.value,
            "decision": ticket.decision,
            "decision_actor": ticket.decision_actor,
            "decision_reason": ticket.decision_reason,
            "final_doc_id": ticket.final_doc_id,
            "confirmed_tags": ticket.confirmed_tags or [],
            "return_target_stage": ticket.return_target_stage,
            "return_reason": ticket.return_reason,
        })
        return payload


# ------------------------------------------------------------------
# ID generators
# ------------------------------------------------------------------
_TICKET_PREFIX = "atck_"
_AUDIT_PREFIX = "aaud_"


def _generate_ticket_id() -> str:
    return _TICKET_PREFIX + secrets.token_hex(12)


def _generate_audit_id() -> str:
    return _AUDIT_PREFIX + secrets.token_hex(12)


def _hash_payload(payload: str) -> str:
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()
