-- Auto-generated schema for Java access service tests.

-- Source of truth: SQLAlchemy models in packages/persistence/src/reality_rag_persistence/models.py

-- and hardcoded DDL for Java-only projection tables.

-- Regenerate with: uv run python scripts/generate_java_test_schema.py


-- api_key_projection
CREATE TABLE IF NOT EXISTS api_key_projection (
    api_key_id VARCHAR(128) PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    agent_type_id VARCHAR(128) NOT NULL,
    knowledge_scopes VARCHAR(2048),
    roles VARCHAR(2048),
    debug_permission BOOLEAN NOT NULL DEFAULT FALSE,
    token_budget_limit INTEGER NOT NULL DEFAULT 4096,
    state VARCHAR(32) NOT NULL DEFAULT 'active',
    expires_at TIMESTAMP,
    projection_version INTEGER NOT NULL DEFAULT 1,
    last_updated_at TIMESTAMP NOT NULL,
    synced_at TIMESTAMP,
    runtime_synced BOOLEAN NOT NULL DEFAULT FALSE
);


-- api_key_projection_idempotency
CREATE TABLE IF NOT EXISTS api_key_projection_idempotency (
    idempotency_key VARCHAR(256) PRIMARY KEY,
    processed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- run_traces
CREATE TABLE IF NOT EXISTS run_traces (
    run_trace_id VARCHAR(128) NOT NULL PRIMARY KEY,
    trace_id VARCHAR(64) NOT NULL,
    run_kind VARCHAR(64) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    collection_id VARCHAR(64) NOT NULL,
    principal_id VARCHAR(128) NOT NULL,
    query_id VARCHAR(128) NOT NULL,
    index_version_id VARCHAR(64) NOT NULL,
    profile_id VARCHAR(64) NOT NULL,
    root_status VARCHAR(32) NOT NULL,
    debug_ref VARCHAR(1024) NOT NULL,
    result_count INTEGER NOT NULL DEFAULT 0,
    source_file_id VARCHAR(64),
    intake_job_id VARCHAR(64),
    final_doc_id VARCHAR(128),
    approval_ticket_id VARCHAR(64),
    extra_json TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);


-- run_steps
CREATE TABLE IF NOT EXISTS run_steps (
    run_step_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(64) NOT NULL,
    step_name VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    summary VARCHAR(4096) NOT NULL,
    details_json TEXT,
    created_at TIMESTAMP
);
