package com.realityrag.access.trace;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.realityrag.access.contracts.KnowledgeContext;
import com.realityrag.access.security.AccessRequestContext;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class LoggingAccessTraceRecorderTest {
    private JdbcTemplate jdbcTemplate;
    private LoggingAccessTraceRecorder recorder;

    @BeforeEach
    void setUp() {
        var dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.h2.Driver");
        dataSource.setUrl("jdbc:h2:mem:access-trace;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        dataSource.setUsername("sa");
        dataSource.setPassword("");
        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS run_traces (
                run_trace_id VARCHAR(128) PRIMARY KEY,
                trace_id VARCHAR(64) NOT NULL,
                run_kind VARCHAR(64) NOT NULL,
                tenant_id VARCHAR(64) NOT NULL,
                collection_id VARCHAR(64) NOT NULL,
                principal_id VARCHAR(128) NOT NULL,
                query_id VARCHAR(128) NOT NULL,
                index_version_id VARCHAR(64) NOT NULL,
                profile_id VARCHAR(64) NOT NULL,
                root_status VARCHAR(32) NOT NULL,
                debug_ref VARCHAR(1024) NOT NULL,
                result_count INTEGER NOT NULL,
                source_file_id VARCHAR(64),
                intake_job_id VARCHAR(64),
                final_doc_id VARCHAR(128),
                approval_ticket_id VARCHAR(64),
                extra_json CLOB,
                created_at TIMESTAMP,
                updated_at TIMESTAMP
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS run_steps (
                run_step_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                trace_id VARCHAR(64) NOT NULL,
                step_name VARCHAR(64) NOT NULL,
                status VARCHAR(32) NOT NULL,
                summary VARCHAR(4096) NOT NULL,
                details_json CLOB,
                created_at TIMESTAMP
            )
            """);
        jdbcTemplate.update("DELETE FROM run_steps");
        jdbcTemplate.update("DELETE FROM run_traces");
        recorder = new LoggingAccessTraceRecorder(jdbcTemplate, new ObjectMapper());
    }

    @Test
    void writesAccessAuditEvidenceToDatabase() {
        var context = new AccessRequestContext(
            "rr-agent-platform-dev",
            "tnt_default",
            "kb_assistant",
            "agent-instance-001",
            List.of("col_default"),
            List.of("agent"),
            Map.of(),
            false,
            "rest",
            4096
        );

        recorder.recordRequestAccepted("qry_access_01", "trc_access_01", context);
        recorder.flush();
        recorder.recordResponse("qry_access_01", "trc_access_01", new KnowledgeContext(
            "qry_access_01",
            Map.of(),
            List.of("idxv_col_default_active"),
            List.of(),
            List.of(new KnowledgeContext.ResultChunk(
                "col_default",
                "doc_001",
                "chk_001",
                "dir_001",
                "text",
                List.of(),
                List.of(),
                1.0d,
                "hybrid_fusion",
                "matched"
            )),
            List.of(),
            List.of(),
            100,
            Map.of("debug_ref", "dbg://retrieval/qry_access_01")
        ));
        recorder.flush();

        Integer traceCount = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM run_traces WHERE run_trace_id = ? AND root_status = ? AND result_count = ?",
            Integer.class,
            "access_qry_access_01",
            "SUCCEEDED",
            1
        );
        assertThat(traceCount).isEqualTo(1);

        String details = jdbcTemplate.queryForObject(
            "SELECT details_json FROM run_steps WHERE trace_id = ? AND step_name = ?",
            String.class,
            "trc_access_01",
            "access.response"
        );
        assertThat(details)
            .contains("idxv_col_default_active")
            .contains("chk_001")
            .contains("doc_001");
    }
}
