package com.realityrag.retrieval.support;

import javax.sql.DataSource;
import org.springframework.jdbc.core.JdbcTemplate;

public final class DbBackedRetrievalTestConfig {
    private DbBackedRetrievalTestConfig() {}

    public static void seed(JdbcTemplate jdbcTemplate) {
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS retrieval_profiles (
                profile_id VARCHAR(64) NOT NULL,
                collection_id VARCHAR(64) NOT NULL,
                profile_version INTEGER NOT NULL,
                profile_hash VARCHAR(128) NOT NULL,
                bm25_weight DOUBLE PRECISION NOT NULL,
                vector_weight DOUBLE PRECISION NOT NULL,
                candidate_top_k INTEGER NOT NULL,
                similarity_threshold DOUBLE PRECISION NOT NULL,
                rerank_enabled BOOLEAN NOT NULL,
                rerank_model VARCHAR(128) NOT NULL,
                fail_policy VARCHAR(32) NOT NULL,
                expansion_policy CLOB,
                pack_budget INTEGER NOT NULL,
                enabled BOOLEAN NOT NULL,
                updated_at TIMESTAMP,
                updated_by VARCHAR(128) NOT NULL,
                PRIMARY KEY (profile_id, collection_id)
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS run_traces (
                run_trace_id VARCHAR(128) PRIMARY KEY,
                trace_id VARCHAR(64) NOT NULL,
                run_kind VARCHAR(64) NOT NULL,
                tenant_id VARCHAR(64) NOT NULL,
                collection_id VARCHAR(64) NOT NULL,
                principal_id VARCHAR(128) NOT NULL,
                query_id VARCHAR(128) NOT NULL,
                index_version_id VARCHAR(64) NOT NULL,
                profile_id VARCHAR(64) NOT NULL,
                root_status VARCHAR(32) NOT NULL,
                debug_ref VARCHAR(1024) NOT NULL,
                result_count INTEGER NOT NULL,
                source_file_id VARCHAR(64),
                intake_job_id VARCHAR(64),
                doc_id VARCHAR(128),
                approval_ticket_id VARCHAR(64),
                extra_json CLOB,
                created_at TIMESTAMP,
                updated_at TIMESTAMP
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS run_steps (
                run_step_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                trace_id VARCHAR(64) NOT NULL,
                step_name VARCHAR(64) NOT NULL,
                status VARCHAR(32) NOT NULL,
                summary VARCHAR(4096) NOT NULL,
                details_json CLOB,
                created_at TIMESTAMP
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS published_documents (
                published_document_id VARCHAR(64) PRIMARY KEY,
                final_doc_id VARCHAR(128) NOT NULL,
                logical_document_id VARCHAR(128) NOT NULL,
                tenant_id VARCHAR(64) NOT NULL,
                collection_id VARCHAR(64) NOT NULL,
                version INTEGER NOT NULL,
                source_content_hash VARCHAR(128) NOT NULL,
                canonical_hash VARCHAR(128) NOT NULL,
                state VARCHAR(32) NOT NULL,
                active_index_version VARCHAR(64) NOT NULL,
                previous_state VARCHAR(32),
                supersedes_doc_id VARCHAR(128),
                created_by_ticket_id VARCHAR(64),
                asset_paths VARCHAR(4096),
                created_at TIMESTAMP,
                updated_at TIMESTAMP
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS index_registry (
                collection_id VARCHAR(64) PRIMARY KEY,
                index_version VARCHAR(64) NOT NULL,
                previous_index_version VARCHAR(64),
                target_index_version VARCHAR(64),
                status VARCHAR(32),
                created_at TIMESTAMP,
                updated_at TIMESTAMP
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS index_versions (
                index_version_id VARCHAR(64) PRIMARY KEY,
                tenant_id VARCHAR(64) NOT NULL,
                collection_id VARCHAR(64) NOT NULL,
                status VARCHAR(32) NOT NULL,
                schema_version VARCHAR(32) NOT NULL,
                index_profile_id VARCHAR(64) NOT NULL,
                chunk_profile_id VARCHAR(64) NOT NULL,
                embedding_model VARCHAR(128) NOT NULL,
                opensearch_index VARCHAR(128) NOT NULL,
                qdrant_collection VARCHAR(128) NOT NULL,
                chunk_count INTEGER NOT NULL,
                created_at TIMESTAMP,
                updated_at TIMESTAMP
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS chunk_registry (
                evidence_id VARCHAR(128) PRIMARY KEY,
                tenant_id VARCHAR(64) NOT NULL,
                collection_id VARCHAR(64) NOT NULL,
                doc_id VARCHAR(128) NOT NULL,
                index_version_id VARCHAR(64) NOT NULL,
                available_int INTEGER NOT NULL,
                visibility VARCHAR(32) NOT NULL,
                payload_json CLOB,
                created_at TIMESTAMP,
                updated_at TIMESTAMP
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS indexed_documents (
                indexed_document_id VARCHAR(64) PRIMARY KEY,
                final_doc_id VARCHAR(128) NOT NULL,
                collection_id VARCHAR(64) NOT NULL,
                index_version VARCHAR(64) NOT NULL,
                parser_id VARCHAR(64) NOT NULL,
                source_suffix VARCHAR(32) NOT NULL,
                chunk_count INTEGER NOT NULL,
                embedding_count INTEGER NOT NULL,
                visible_chunk_count INTEGER NOT NULL,
                hidden_chunk_count INTEGER NOT NULL,
                has_toc_chunk BOOLEAN NOT NULL,
                has_parent_chunk BOOLEAN NOT NULL,
                document_metadata CLOB,
                outline CLOB,
                state VARCHAR(32) NOT NULL,
                activated_at TIMESTAMP,
                created_at TIMESTAMP,
                updated_at TIMESTAMP
            )
            """);

        jdbcTemplate.update("DELETE FROM chunk_registry");
        jdbcTemplate.update("DELETE FROM indexed_documents");
        jdbcTemplate.update("DELETE FROM index_versions");
        jdbcTemplate.update("DELETE FROM index_registry");
        jdbcTemplate.update("DELETE FROM published_documents");
        jdbcTemplate.update("DELETE FROM retrieval_profiles");
        jdbcTemplate.update("DELETE FROM run_steps");
        jdbcTemplate.update("DELETE FROM run_traces");

        jdbcTemplate.update(
            """
                INSERT INTO retrieval_profiles (
                    profile_id, collection_id, profile_version, profile_hash, bm25_weight, vector_weight,
                    candidate_top_k, similarity_threshold, rerank_enabled, rerank_model, fail_policy,
                    expansion_policy, pack_budget, enabled, updated_at, updated_by
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?)
                """,
            "ret_default",
            "col_policy",
            1,
            "sha256:ret-default-test",
            0.55d,
            0.45d,
            20,
            0.2d,
            true,
            "rerank-v1",
            "fail_closed",
            "{\"adjacent_window\":1}",
            1200,
            true,
            "test"
        );
        jdbcTemplate.update(
            """
                INSERT INTO retrieval_profiles (
                    profile_id, collection_id, profile_version, profile_hash, bm25_weight, vector_weight,
                    candidate_top_k, similarity_threshold, rerank_enabled, rerank_model, fail_policy,
                    expansion_policy, pack_budget, enabled, updated_at, updated_by
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?)
                """,
            "ret_default",
            "col_handbook",
            1,
            "sha256:ret-default-test",
            0.55d,
            0.45d,
            20,
            0.2d,
            true,
            "rerank-v1",
            "fail_closed",
            "{\"adjacent_window\":1}",
            1200,
            true,
            "test"
        );

        jdbcTemplate.update(
            """
                INSERT INTO published_documents (
                    published_document_id, final_doc_id, logical_document_id, tenant_id, collection_id, version,
                    source_content_hash, canonical_hash, state, active_index_version, created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """,
            "pub_doc_policy_01",
            "doc_expense_policy",
            "ld_expense_policy",
            "tnt_default",
            "col_policy",
            1,
            "sha256:doc_expense_policy_src",
            "sha256:doc_expense_policy_canonical",
            "PUBLISHED",
            "idxv_col_policy_active"
        );
        jdbcTemplate.update(
            """
                INSERT INTO published_documents (
                    published_document_id, final_doc_id, logical_document_id, tenant_id, collection_id, version,
                    source_content_hash, canonical_hash, state, active_index_version, created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """,
            "pub_doc_handbook_01",
            "doc_travel_handbook",
            "ld_travel_handbook",
            "tnt_default",
            "col_handbook",
            1,
            "sha256:doc_travel_handbook_src",
            "sha256:doc_travel_handbook_canonical",
            "PUBLISHED",
            "idxv_col_handbook_active"
        );

        jdbcTemplate.update(
            """
                INSERT INTO index_registry (
                    collection_id, index_version, status, created_at, updated_at
                ) VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """,
            "col_policy",
            "idxv_col_policy_active",
            "ACTIVE"
        );
        jdbcTemplate.update(
            """
                INSERT INTO index_registry (
                    collection_id, index_version, status, created_at, updated_at
                ) VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """,
            "col_handbook",
            "idxv_col_handbook_active",
            "ACTIVE"
        );
        jdbcTemplate.update(
            """
                INSERT INTO index_versions (
                    index_version_id, tenant_id, collection_id, status, schema_version, index_profile_id,
                    chunk_profile_id, embedding_model, opensearch_index, qdrant_collection, chunk_count,
                    created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """,
            "idxv_col_policy_active",
            "tnt_default",
            "col_policy",
            "READY",
            "2026-05-26",
            "ragflow",
            "chunk_default",
            "BAAI/bge-m3",
            "os_col_policy_active",
            "qd_col_policy_active",
            1
        );
        jdbcTemplate.update(
            """
                INSERT INTO index_versions (
                    index_version_id, tenant_id, collection_id, status, schema_version, index_profile_id,
                    chunk_profile_id, embedding_model, opensearch_index, qdrant_collection, chunk_count,
                    created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """,
            "idxv_col_handbook_active",
            "tnt_default",
            "col_handbook",
            "READY",
            "2026-05-26",
            "ragflow",
            "chunk_default",
            "BAAI/bge-m3",
            "os_col_handbook_active",
            "qd_col_handbook_active",
            1
        );

        jdbcTemplate.update(
            """
                INSERT INTO chunk_registry (
                    evidence_id, tenant_id, collection_id, doc_id, index_version_id, available_int, visibility, payload_json, created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """,
            "chk_doc_expense_policy_idxv_col_policy_active_0001",
            "tnt_default",
            "col_policy",
            "doc_expense_policy",
            "idxv_col_policy_active",
            1,
            "internal",
            "{\"collection_id\":\"col_policy\",\"final_doc_id\":\"doc_expense_policy\",\"index_version_id\":\"idxv_col_policy_active\",\"document_index_revision_id\":\"dir_doc_expense_policy_01\",\"chunk_id\":\"chk_doc_expense_policy_idxv_col_policy_active_0001\",\"display_text\":\"Approved expenses are reimbursable when they follow the expense policy.\",\"vector_text\":\"Expense Policy Approved expenses are reimbursable when they follow the expense policy.\",\"section_path\":[\"Expense Policy\"],\"page_spans\":[{\"page_from\":1,\"page_to\":1}],\"published_document_state\":\"PUBLISHED\",\"visibility\":\"internal\",\"allowed_principal_ids\":[],\"allowed_groups\":[\"finance\"],\"citation_payload\":{\"collection_id\":\"col_policy\",\"final_doc_id\":\"doc_expense_policy\",\"anchor\":\"page:1:span:0-67\"},\"metadata\":{}}"
        );
        jdbcTemplate.update(
            """
                INSERT INTO chunk_registry (
                    evidence_id, tenant_id, collection_id, doc_id, index_version_id, available_int, visibility, payload_json, created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """,
            "chk_doc_expense_policy_idxv_col_policy_old_0001",
            "tnt_default",
            "col_policy",
            "doc_expense_policy",
            "idxv_col_policy_old",
            1,
            "internal",
            "{\"collection_id\":\"col_policy\",\"final_doc_id\":\"doc_expense_policy\",\"index_version_id\":\"idxv_col_policy_old\",\"document_index_revision_id\":\"dir_doc_expense_policy_old\",\"chunk_id\":\"chk_doc_expense_policy_idxv_col_policy_old_0001\",\"display_text\":\"This old index chunk must not be returned.\",\"vector_text\":\"old expense policy chunk\",\"section_path\":[\"Expense Policy\"],\"page_spans\":[{\"page_from\":1,\"page_to\":1}],\"published_document_state\":\"PUBLISHED\",\"visibility\":\"internal\",\"allowed_principal_ids\":[],\"allowed_groups\":[\"finance\"],\"citation_payload\":{},\"metadata\":{}}"
        );
        jdbcTemplate.update(
            """
                INSERT INTO chunk_registry (
                    evidence_id, tenant_id, collection_id, doc_id, index_version_id, available_int, visibility, payload_json, created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """,
            "chk_doc_travel_handbook_idxv_col_handbook_active_0007",
            "tnt_default",
            "col_handbook",
            "doc_travel_handbook",
            "idxv_col_handbook_active",
            1,
            "internal",
            "{\"collection_id\":\"col_handbook\",\"final_doc_id\":\"doc_travel_handbook\",\"index_version_id\":\"idxv_col_handbook_active\",\"document_index_revision_id\":\"dir_doc_travel_handbook_02\",\"chunk_id\":\"chk_doc_travel_handbook_idxv_col_handbook_active_0007\",\"display_text\":\"Travel reimbursements are reimbursable with manager approval for out-of-policy items.\",\"vector_text\":\"Travel Handbook Travel reimbursements are reimbursable with manager approval for out-of-policy items.\",\"section_path\":[\"Travel Handbook\",\"Reimbursement\"],\"page_spans\":[{\"page_from\":3,\"page_to\":3}],\"published_document_state\":\"PUBLISHED\",\"visibility\":\"internal\",\"allowed_principal_ids\":[],\"allowed_groups\":[\"finance\",\"hr\"],\"citation_payload\":{\"collection_id\":\"col_handbook\",\"final_doc_id\":\"doc_travel_handbook\",\"anchor\":\"page:3:span:0-73\"},\"metadata\":{}}"
        );
    }

    public static JdbcTemplate jdbc(DataSource dataSource) {
        return new JdbcTemplate(dataSource);
    }
}
