package com.realityrag.retrieval.support;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.realityrag.retrieval.profiles.FileProjectionRetrievalProfileStore;
import com.realityrag.retrieval.profiles.RetrievalProfileStore;
import com.realityrag.retrieval.scope.sources.FileProjectionIndexRegistrySource;
import com.realityrag.retrieval.scope.sources.FileProjectionPublishedDocumentSource;
import com.realityrag.retrieval.scope.sources.IndexRegistrySource;
import com.realityrag.retrieval.scope.sources.PublishedDocumentSource;
import com.realityrag.retrieval.store.FileProjectionKnowledgeStore;
import com.realityrag.retrieval.store.KnowledgeStore;
import com.realityrag.retrieval.toc.DocumentTocSource;
import com.realityrag.retrieval.toc.FileProjectionDocumentTocSource;
import java.nio.file.Path;
import javax.sql.DataSource;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

@TestConfiguration
public class FileFixtureRetrievalTestConfig {
    @Bean
    @Primary
    public DataSource fixtureDataSource() {
        var dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.h2.Driver");
        dataSource.setUrl("jdbc:h2:mem:retrieval-file-fixture;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        dataSource.setUsername("sa");
        dataSource.setPassword("");
        return dataSource;
    }

    @Bean
    @Primary
    public JdbcTemplate fixtureJdbcTemplate(DataSource fixtureDataSource) {
        var jdbcTemplate = new JdbcTemplate(fixtureDataSource);
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS run_traces (
                run_trace_id VARCHAR(128) PRIMARY KEY,
                trace_id VARCHAR(64) NOT NULL,
                run_kind VARCHAR(64) NOT NULL,
                tenant_id VARCHAR(64) NOT NULL,
                collection_id VARCHAR(64) NOT NULL,
                principal_id VARCHAR(128) NOT NULL,
                query_id VARCHAR(128) NOT NULL,
                index_version_id VARCHAR(64) NOT NULL,
                profile_id VARCHAR(64) NOT NULL,
                root_status VARCHAR(32) NOT NULL,
                debug_ref VARCHAR(1024) NOT NULL,
                result_count INTEGER NOT NULL,
                source_file_id VARCHAR(64),
                intake_job_id VARCHAR(64),
                doc_id VARCHAR(128),
                approval_ticket_id VARCHAR(64),
                extra_json CLOB,
                created_at TIMESTAMP,
                updated_at TIMESTAMP
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS run_steps (
                run_step_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                trace_id VARCHAR(64) NOT NULL,
                step_name VARCHAR(64) NOT NULL,
                status VARCHAR(32) NOT NULL,
                summary VARCHAR(4096) NOT NULL,
                details_json CLOB,
                created_at TIMESTAMP
            )
            """);
        return jdbcTemplate;
    }

    @Bean
    @Primary
    public PublishedDocumentSource publishedDocumentSource(
        @Value("${retrieval.data.published-documents-file}") String publishedDocumentsFile,
        ObjectMapper objectMapper
    ) {
        return new FileProjectionPublishedDocumentSource(Path.of(publishedDocumentsFile), objectMapper);
    }

    @Bean
    @Primary
    public IndexRegistrySource indexRegistrySource(
        @Value("${retrieval.data.index-registry-file}") String indexRegistryFile,
        ObjectMapper objectMapper
    ) {
        return new FileProjectionIndexRegistrySource(Path.of(indexRegistryFile), objectMapper);
    }

    @Bean
    @Primary
    public RetrievalProfileStore retrievalProfileStore(
        @Value("${retrieval.data.retrieval-profiles-file}") String retrievalProfilesFile,
        ObjectMapper objectMapper
    ) {
        return new FileProjectionRetrievalProfileStore(Path.of(retrievalProfilesFile), objectMapper);
    }

    @Bean
    @Primary
    public KnowledgeStore knowledgeStore(
        @Value("${retrieval.data.indexed-chunks-file}") String indexedChunksFile,
        ObjectMapper objectMapper
    ) {
        return new FileProjectionKnowledgeStore(Path.of(indexedChunksFile), objectMapper);
    }

    @Bean
    @Primary
    public DocumentTocSource documentTocSource(
        @Value("${retrieval.data.document-toc-file:}") String documentTocFile,
        ObjectMapper objectMapper
    ) {
        if (documentTocFile == null || documentTocFile.isBlank()) {
            return (collectionId, finalDocId) -> java.util.List.of();
        }
        return new FileProjectionDocumentTocSource(Path.of(documentTocFile), objectMapper);
    }
}
