#!/usr/bin/env python3
"""
Generate PostgreSQL DDL for Java test schema.sql from SQLAlchemy models.

Two sources of truth:
  1. SQLAlchemy models (for tables used by both Python and Java)
  2. Hardcoded DDL (for Java-only projection tables not mirrored in models.py)

Usage:
  uv run python scripts/generate_java_test_schema.py                # write to both modules
  uv run python scripts/generate_java_test_schema.py --check         # diff-only, exit 1 on mismatch
  uv run python scripts/generate_java_test_schema.py --output-dir access  # single module
"""

import argparse
import re
import sys
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# SQLAlchemy type → PostgreSQL DDL type mapping
# ---------------------------------------------------------------------------

PG_TYPE_MAP = {
    "String": "VARCHAR({length})",
    "Integer": "INTEGER",
    "Float": "DOUBLE PRECISION",
    "Boolean": "BOOLEAN",
    "DateTime": "TIMESTAMP",
    "JSON": "TEXT",
    "LargeBinary": "BYTEA",
}


def sa_type_to_pg(col) -> str:
    """Convert a SQLAlchemy Column's type to a PostgreSQL DDL type string."""
    col_type = col.type
    type_name = type(col_type).__name__

    if type_name == "String":
        length = col_type.length or 255
        return f"VARCHAR({length})"
    elif type_name == "Integer":
        return "INTEGER"
    elif type_name == "Float":
        return "DOUBLE PRECISION"
    elif type_name == "Boolean":
        return "BOOLEAN"
    elif type_name in ("DateTime", "TIMESTAMP"):
        return "TIMESTAMP"
    elif type_name == "JSON":
        return "TEXT"
    elif type_name == "LargeBinary":
        return "BYTEA"
    else:
        raise ValueError(f"Unknown SA type {type_name} for column {col.name}")


def column_ddl(col, indent: str = "    ") -> str:
    """Generate a single column DDL line from a SQLAlchemy Column."""
    col_type_name = type(col.type).__name__
    parts = [indent, col.name, " ", sa_type_to_pg(col)]

    if not col.nullable:
        parts.append(" NOT NULL")

    # Autoincrement identity for Integer PKs
    is_auto_pk = col.autoincrement and col.primary_key and col_type_name == "Integer"

    if is_auto_pk:
        parts.append(" GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
        return "".join(parts)

    # Default values
    if col.default is not None and hasattr(col.default, "arg"):
        default = col.default.arg
        if isinstance(default, bool):
            parts.append(f" DEFAULT {'true' if default else 'false'}")
        elif isinstance(default, int):
            parts.append(f" DEFAULT {default}")
        elif isinstance(default, str):
            if default in ("", None):
                pass
            else:
                parts.append(f" DEFAULT '{default}'")
        elif isinstance(default, float):
            parts.append(f" DEFAULT {default}")
        elif callable(default):
            pass

    # Only inline PRIMARY KEY for single-column PKs, not composite
    if col.primary_key:
        # Check how many PK columns this table has
        pk_count = sum(1 for c in col.table.columns if c.primary_key)
        if pk_count == 1:
            parts.append(" PRIMARY KEY")

    return "".join(parts)


# ---------------------------------------------------------------------------
# Hardcoded DDL for Java-only projection tables (no SQLAlchemy model)
# ---------------------------------------------------------------------------

JAVA_ONLY_TABLES: dict[str, str] = {
    "api_key_projection": """CREATE TABLE IF NOT EXISTS api_key_projection (
    api_key_id VARCHAR(128) PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    agent_type_id VARCHAR(128) NOT NULL,
    knowledge_scopes VARCHAR(2048),
    roles VARCHAR(2048),
    debug_permission BOOLEAN NOT NULL DEFAULT FALSE,
    token_budget_limit INTEGER NOT NULL DEFAULT 4096,
    state VARCHAR(32) NOT NULL DEFAULT 'active',
    expires_at TIMESTAMP,
    projection_version INTEGER NOT NULL DEFAULT 1,
    last_updated_at TIMESTAMP NOT NULL,
    synced_at TIMESTAMP,
    runtime_synced BOOLEAN NOT NULL DEFAULT FALSE
);
""",
    "api_key_projection_idempotency": """CREATE TABLE IF NOT EXISTS api_key_projection_idempotency (
    idempotency_key VARCHAR(256) PRIMARY KEY,
    processed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
""",
    "index_projection_idempotency": """CREATE TABLE IF NOT EXISTS index_projection_idempotency (
    idempotency_key VARCHAR(512) PRIMARY KEY,
    processed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
""",
}

# ---------------------------------------------------------------------------
# Module → table mapping
# ---------------------------------------------------------------------------

MODULE_TABLES: dict[str, list[str]] = {
    "access": [
        # Java-only tables (hardcoded)
        "api_key_projection",
        "api_key_projection_idempotency",
        # Tables from SQLAlchemy models
        "run_traces",
        "run_steps",
    ],
    "retrieval": [
        # Java-only tables (hardcoded)
        "index_projection_idempotency",
        # Tables from SQLAlchemy models
        "run_traces",
        "run_steps",
        "index_versions",
        "index_registry",
        "published_documents",
        "chunk_registry",
        "retrieval_profiles",
        "indexed_documents",
    ],
}

# ---------------------------------------------------------------------------
# Main generation logic
# ---------------------------------------------------------------------------


def load_models():
    """Dynamically import SQLAlchemy models from the persistence package.

    Returns a dict mapping table_name → SQLAlchemy model class.
    """
    # Add the project root to sys.path
    project_root = Path(__file__).resolve().parent.parent
    models_path = project_root / "packages" / "persistence" / "src"
    sys.path.insert(0, str(models_path))

    from reality_rag_persistence.models import Base

    # Collect all model classes registered on Base
    models = {}
    for mapper in Base.registry.mappers:
        cls = mapper.class_
        table_name = cls.__tablename__
        models[table_name] = cls
    return models


def generate_table_ddl(table_name: str, model_cls) -> str:
    """Generate CREATE TABLE DDL from a SQLAlchemy model class."""
    cols = []
    pk_constraints = []
    for col in model_cls.__table__.columns:
        col_ddl = column_ddl(col)

        # Track composite primary keys separately
        if col.primary_key and not col.autoincrement:
            # Single PK is inlined — skip composite handling
            pass

        cols.append(col_ddl)

    # Handle composite primary keys
    pk_cols = [c for c in model_cls.__table__.columns if c.primary_key]
    if len(pk_cols) > 1:
        # Exclude autoincrement from composite PK
        pk_names = [c.name for c in pk_cols]
        pk_parts = ", ".join(pk_names)
        pk_constraints.append(f"    PRIMARY KEY ({pk_parts})")

    col_lines = ",\n".join(cols + pk_constraints)
    return f"CREATE TABLE IF NOT EXISTS {table_name} (\n{col_lines}\n);\n"


def generate_module_schema(module: str, models: dict) -> str:
    """Generate the full schema.sql content for one module."""
    lines = [
        f"-- Auto-generated schema for Java {module} service tests.\n",
        f"-- Source of truth: SQLAlchemy models in packages/persistence/src/reality_rag_persistence/models.py\n",
        f"-- and hardcoded DDL for Java-only projection tables.\n",
        f"-- Regenerate with: uv run python scripts/generate_java_test_schema.py\n",
    ]

    for table_name in MODULE_TABLES[module]:
        lines.append(f"\n-- {table_name}")
        if table_name in JAVA_ONLY_TABLES:
            lines.append(JAVA_ONLY_TABLES[table_name])
        elif table_name in models:
            lines.append(generate_table_ddl(table_name, models[table_name]))
        else:
            print(f"WARNING: table '{table_name}' not found in models or hardcoded tables — skipping", file=sys.stderr)

    return "\n".join(lines)


def read_current_schema(path: Path) -> Optional[str]:
    """Read existing schema.sql, or None."""
    if path.exists():
        return path.read_text(encoding="utf-8")
    return None


def main():
    parser = argparse.ArgumentParser(description="Generate Java test schema.sql from SQLAlchemy models")
    parser.add_argument("--check", action="store_true", help="Check-only mode: diff against existing, exit 1 on mismatch")
    parser.add_argument("--output-dir", choices=["access", "retrieval"], help="Generate for a single module only")
    args = parser.parse_args()

    project_root = Path(__file__).resolve().parent.parent
    models = load_models()

    modules = [args.output_dir] if args.output_dir else ["access", "retrieval"]
    any_mismatch = False

    for module in modules:
        generated = generate_module_schema(module, models)
        schema_path = project_root / "services" / module / "src" / "test" / "resources" / "schema.sql"

        if args.check:
            existing = read_current_schema(schema_path)
            if existing is None:
                print(f"[MISMATCH] {schema_path}: file does not exist", file=sys.stderr)
                any_mismatch = True
                continue

            if existing.strip() != generated.strip():
                print(f"[MISMATCH] {schema_path}: content differs from generated DDL", file=sys.stderr)
                # Show diff
                import difflib
                diff = difflib.unified_diff(
                    existing.splitlines(),
                    generated.splitlines(),
                    fromfile=str(schema_path),
                    tofile="generated",
                    lineterm="",
                )
                for line in diff:
                    print(line, file=sys.stderr)
                any_mismatch = True
            else:
                print(f"[OK] {schema_path}")
        else:
            schema_path.parent.mkdir(parents=True, exist_ok=True)
            schema_path.write_text(generated, encoding="utf-8")
            print(f"[WRITE] {schema_path}")

    if args.check and any_mismatch:
        sys.exit(1)


if __name__ == "__main__":
    main()
