"""initial schema

Revision ID: 6ad388f63227
Revises: 
Create Date: 2026-06-12 21:42:37.146973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad388f63227'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('clearance_level', sa.Integer(), nullable=True),
    sa.Column('allowed_tenants', sa.JSON(), nullable=True),
    sa.Column('allowed_collections', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('approval_tickets',
    sa.Column('ticket_id', sa.String(length=64), nullable=False),
    sa.Column('intake_job_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('approval_round', sa.Integer(), nullable=False),
    sa.Column('preliminary_doc_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('routing_recommendation', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('decision_actor', sa.String(length=128), nullable=True),
    sa.Column('decision_reason', sa.String(length=2048), nullable=True),
    sa.Column('final_doc_id', sa.String(length=128), nullable=True),
    sa.Column('confirmed_tags', sa.JSON(), nullable=True),
    sa.Column('return_target_stage', sa.String(length=32), nullable=True),
    sa.Column('return_reason', sa.String(length=2048), nullable=True),
    sa.Column('version_decision', sa.String(length=32), nullable=True),
    sa.Column('supersedes_final_doc_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('ticket_id'),
    sa.UniqueConstraint('intake_job_id', 'approval_round', name='uix_approval_ticket_job_round')
    )
    op.create_table('chunk_registry',
    sa.Column('chunk_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('final_doc_id', sa.String(length=128), nullable=False),
    sa.Column('index_version_id', sa.String(length=64), nullable=False),
    sa.Column('available_int', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index('ix_chunk_registry_collection_version', 'chunk_registry', ['collection_id', 'index_version_id'], unique=False)
    op.create_index('ix_chunk_registry_final_doc_version', 'chunk_registry', ['final_doc_id', 'index_version_id'], unique=False)
    op.create_index('ix_chunk_registry_tenant_collection', 'chunk_registry', ['tenant_id', 'collection_id'], unique=False)
    op.create_table('consumer_idempotency',
    sa.Column('record_id', sa.String(length=64), nullable=False),
    sa.Column('consumer_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=512), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index('ix_consumer_idempotency_key', 'consumer_idempotency', ['consumer_id', 'idempotency_key'], unique=False)
    op.create_index('ix_consumer_idempotency_pk', 'consumer_idempotency', ['consumer_id', 'event_id'], unique=True)
    op.create_table('index_registry',
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('index_version', sa.String(length=64), nullable=False),
    sa.Column('previous_index_version', sa.String(length=64), nullable=True),
    sa.Column('target_index_version', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('collection_id')
    )
    op.create_table('index_versions',
    sa.Column('index_version_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('index_profile_id', sa.String(length=64), nullable=False),
    sa.Column('chunk_profile_id', sa.String(length=64), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('opensearch_index', sa.String(length=128), nullable=False),
    sa.Column('qdrant_collection', sa.String(length=128), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('previous_active_index_version_id', sa.String(length=64), nullable=True),
    sa.Column('replaced_by_index_version_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleaned_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('index_version_id')
    )
    op.create_index('ix_index_versions_collection', 'index_versions', ['collection_id'], unique=False)
    op.create_index('ix_index_versions_status', 'index_versions', ['status'], unique=False)
    op.create_table('indexed_documents',
    sa.Column('indexed_document_id', sa.String(length=256), nullable=False),
    sa.Column('final_doc_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('index_version', sa.String(length=64), nullable=False),
    sa.Column('parser_id', sa.String(length=64), nullable=False),
    sa.Column('source_suffix', sa.String(length=32), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('embedding_count', sa.Integer(), nullable=False),
    sa.Column('visible_chunk_count', sa.Integer(), nullable=False),
    sa.Column('hidden_chunk_count', sa.Integer(), nullable=False),
    sa.Column('has_toc_chunk', sa.Boolean(), nullable=False),
    sa.Column('has_parent_chunk', sa.Boolean(), nullable=False),
    sa.Column('document_metadata', sa.JSON(), nullable=True),
    sa.Column('outline', sa.JSON(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('indexed_document_id'),
    sa.UniqueConstraint('final_doc_id', 'index_version', name='uix_indexed_doc_version')
    )
    op.create_index('ix_indexed_docs_collection_version', 'indexed_documents', ['collection_id', 'index_version'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('source_files', sa.JSON(), nullable=True),
    sa.Column('source_file_ids', sa.JSON(), nullable=True),
    sa.Column('conversion_report', sa.JSON(), nullable=True),
    sa.Column('report_asset_path', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('intake_jobs',
    sa.Column('intake_job_id', sa.String(length=64), nullable=False),
    sa.Column('source_file_id', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(length=32), nullable=True),
    sa.Column('preliminary_doc_id', sa.String(length=128), nullable=True),
    sa.Column('review_id', sa.String(length=64), nullable=True),
    sa.Column('ticket_id', sa.String(length=64), nullable=True),
    sa.Column('final_doc_id', sa.String(length=128), nullable=True),
    sa.Column('publish_id', sa.String(length=64), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('intake_job_id'),
    sa.UniqueConstraint('source_file_id')
    )
    op.create_table('jobs',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=True),
    sa.Column('doc_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('llm_call_log',
    sa.Column('llm_call_id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('intake_job_id', sa.String(length=64), nullable=False),
    sa.Column('stage_task_id', sa.String(length=64), nullable=False),
    sa.Column('review_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('request_hash', sa.String(length=128), nullable=False),
    sa.Column('response_hash', sa.String(length=128), nullable=True),
    sa.Column('input_token_count', sa.Integer(), nullable=True),
    sa.Column('output_token_count', sa.Integer(), nullable=True),
    sa.Column('total_token_count', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('json_parse_success', sa.Boolean(), nullable=False),
    sa.Column('schema_validation_success', sa.Boolean(), nullable=False),
    sa.Column('redaction_before_send', sa.Boolean(), nullable=False),
    sa.Column('external_model_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('llm_call_id')
    )
    op.create_index('ix_llm_call_created', 'llm_call_log', ['created_at'], unique=False)
    op.create_index('ix_llm_call_intake_job', 'llm_call_log', ['intake_job_id'], unique=False)
    op.create_index('ix_llm_call_status', 'llm_call_log', ['status'], unique=False)
    op.create_index('ix_llm_call_trace_id', 'llm_call_log', ['trace_id'], unique=False)
    op.create_table('llm_cost_daily',
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('avg_latency_ms', sa.Integer(), nullable=True),
    sa.Column('p95_latency_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date', 'provider', 'model_name', 'model_version', 'prompt_version', 'collection_id', 'visibility')
    )
    op.create_table('object_blobs',
    sa.Column('object_id', sa.String(length=128), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('ref_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('object_id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_table('ops_audit_log',
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('command_id', sa.String(length=128), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=512), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('before_state', sa.String(length=256), nullable=True),
    sa.Column('after_state', sa.String(length=256), nullable=True),
    sa.Column('reason', sa.String(length=2048), nullable=True),
    sa.Column('payload_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_ops_audit_actor', 'ops_audit_log', ['actor_id'], unique=False)
    op.create_index('ix_ops_audit_created', 'ops_audit_log', ['created_at'], unique=False)
    op.create_index('ix_ops_audit_idempotency', 'ops_audit_log', ['idempotency_key'], unique=False)
    op.create_index('ix_ops_audit_target', 'ops_audit_log', ['target_type', 'target_id'], unique=False)
    op.create_index('ix_ops_audit_trace', 'ops_audit_log', ['trace_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.String(length=128), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=512), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_outbox_aggregate', 'outbox_events', ['aggregate_type', 'aggregate_id'], unique=False)
    op.create_index('ix_outbox_status_next_attempt', 'outbox_events', ['status', 'next_attempt_at'], unique=False)
    op.create_table('parse_snapshots',
    sa.Column('parse_snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('source_file_id', sa.String(length=64), nullable=False),
    sa.Column('source_binary_ref', sa.String(length=2048), nullable=False),
    sa.Column('source_filename', sa.String(length=512), nullable=False),
    sa.Column('source_suffix', sa.String(length=32), nullable=False),
    sa.Column('parser_id', sa.String(length=64), nullable=False),
    sa.Column('parser_backend', sa.String(length=64), nullable=False),
    sa.Column('collection_parser_config', sa.JSON(), nullable=True),
    sa.Column('parser_config', sa.JSON(), nullable=True),
    sa.Column('input_hash', sa.String(length=128), nullable=False),
    sa.Column('preview_text', sa.Text(), nullable=False),
    sa.Column('upstream_chunks', sa.JSON(), nullable=True),
    sa.Column('outline', sa.JSON(), nullable=True),
    sa.Column('document_metadata', sa.JSON(), nullable=True),
    sa.Column('chunk_preview', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('decision_reason', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('parse_snapshot_id')
    )
    op.create_index('ix_parse_snapshots_collection', 'parse_snapshots', ['collection_id'], unique=False)
    op.create_index('ix_parse_snapshots_source_file', 'parse_snapshots', ['source_file_id'], unique=False)
    op.create_table('parser_profiles',
    sa.Column('parser_profile_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('parser_id', sa.String(length=64), nullable=False),
    sa.Column('parser_config', sa.JSON(), nullable=True),
    sa.Column('runtime_canonical_config', sa.JSON(), nullable=True),
    sa.Column('profile_hash', sa.String(length=128), nullable=False),
    sa.Column('validator_version', sa.String(length=64), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('parser_profile_id')
    )
    op.create_table('reindex_jobs',
    sa.Column('reindex_job_id', sa.String(length=64), nullable=False),
    sa.Column('final_doc_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('source_index_version', sa.String(length=64), nullable=False),
    sa.Column('target_index_version', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('index_build_job_id', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('reindex_job_id')
    )
    op.create_table('retrieval_profiles',
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('profile_hash', sa.String(length=128), nullable=False),
    sa.Column('bm25_weight', sa.Float(), nullable=False),
    sa.Column('vector_weight', sa.Float(), nullable=False),
    sa.Column('candidate_top_k', sa.Integer(), nullable=False),
    sa.Column('similarity_threshold', sa.Float(), nullable=False),
    sa.Column('rerank_enabled', sa.Boolean(), nullable=False),
    sa.Column('rerank_model', sa.String(length=128), nullable=False),
    sa.Column('fail_policy', sa.String(length=32), nullable=False),
    sa.Column('expansion_policy', sa.JSON(), nullable=True),
    sa.Column('pack_budget', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('profile_id', 'collection_id')
    )
    op.create_index('ix_retrieval_profiles_collection', 'retrieval_profiles', ['collection_id'], unique=False)
    op.create_index('ix_retrieval_profiles_enabled', 'retrieval_profiles', ['enabled'], unique=False)
    op.create_table('retrieval_profiles_admin',
    sa.Column('retrieval_profile_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('profile_config', sa.JSON(), nullable=True),
    sa.Column('runtime_canonical_config', sa.JSON(), nullable=True),
    sa.Column('profile_hash', sa.String(length=128), nullable=False),
    sa.Column('validator_version', sa.String(length=64), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('retrieval_profile_id')
    )
    op.create_table('review_quality_feedback',
    sa.Column('feedback_id', sa.String(length=64), nullable=False),
    sa.Column('review_id', sa.String(length=64), nullable=False),
    sa.Column('intake_job_id', sa.String(length=64), nullable=False),
    sa.Column('ticket_id', sa.String(length=64), nullable=True),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('routing_recommendation', sa.String(length=32), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('pii_count_by_type', sa.JSON(), nullable=True),
    sa.Column('pii_count_by_severity', sa.JSON(), nullable=True),
    sa.Column('visibility_conflict', sa.Boolean(), nullable=False),
    sa.Column('visibility_conflict_type', sa.String(length=64), nullable=True),
    sa.Column('approval_decision', sa.String(length=32), nullable=True),
    sa.Column('auto_approved', sa.Boolean(), nullable=False),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.Column('return_target_stage', sa.String(length=32), nullable=True),
    sa.Column('return_reason_code', sa.String(length=64), nullable=True),
    sa.Column('approver_changed_tags', sa.Boolean(), nullable=True),
    sa.Column('approved_after_review_failure', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index('ix_review_feedback_intake_job', 'review_quality_feedback', ['intake_job_id'], unique=False)
    op.create_index('ix_review_feedback_review_id', 'review_quality_feedback', ['review_id'], unique=False)
    op.create_table('run_steps',
    sa.Column('run_step_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('step_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.String(length=4096), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('run_step_id')
    )
    op.create_index('ix_run_steps_created_at', 'run_steps', ['created_at'], unique=False)
    op.create_index('ix_run_steps_trace_id', 'run_steps', ['trace_id'], unique=False)
    op.create_table('run_traces',
    sa.Column('run_trace_id', sa.String(length=128), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('run_kind', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('principal_id', sa.String(length=128), nullable=False),
    sa.Column('query_id', sa.String(length=128), nullable=False),
    sa.Column('index_version_id', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('root_status', sa.String(length=32), nullable=False),
    sa.Column('debug_ref', sa.String(length=1024), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.String(length=64), nullable=True),
    sa.Column('intake_job_id', sa.String(length=64), nullable=True),
    sa.Column('final_doc_id', sa.String(length=128), nullable=True),
    sa.Column('approval_ticket_id', sa.String(length=64), nullable=True),
    sa.Column('extra_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('run_trace_id')
    )
    op.create_index('ix_run_traces_final_doc', 'run_traces', ['final_doc_id'], unique=False)
    op.create_index('ix_run_traces_intake_job', 'run_traces', ['intake_job_id'], unique=False)
    op.create_index('ix_run_traces_source_file', 'run_traces', ['source_file_id'], unique=False)
    op.create_index('ix_run_traces_trace_id', 'run_traces', ['trace_id'], unique=False)
    op.create_table('telemetry_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('intake_job_id', sa.String(length=64), nullable=True),
    sa.Column('source_file_id', sa.String(length=64), nullable=True),
    sa.Column('collection_id', sa.String(length=64), nullable=True),
    sa.Column('visibility', sa.String(length=16), nullable=True),
    sa.Column('stage_name', sa.String(length=32), nullable=True),
    sa.Column('stage_task_id', sa.String(length=64), nullable=True),
    sa.Column('ticket_id', sa.String(length=64), nullable=True),
    sa.Column('final_doc_id', sa.String(length=128), nullable=True),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('component_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('attributes_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_telemetry_event_name', 'telemetry_events', ['event_name'], unique=False)
    op.create_index('ix_telemetry_event_time', 'telemetry_events', ['event_time'], unique=False)
    op.create_index('ix_telemetry_intake_job', 'telemetry_events', ['intake_job_id'], unique=False)
    op.create_index('ix_telemetry_trace_id', 'telemetry_events', ['trace_id'], unique=False)
    op.create_table('tenants',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('trace_artifacts',
    sa.Column('trace_artifact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('artifact_ref', sa.String(length=2048), nullable=False),
    sa.Column('artifact_kind', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.String(length=4096), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('trace_artifact_id')
    )
    op.create_index('ix_trace_artifacts_created_at', 'trace_artifacts', ['created_at'], unique=False)
    op.create_index('ix_trace_artifacts_kind', 'trace_artifacts', ['artifact_kind'], unique=False)
    op.create_index('ix_trace_artifacts_trace_id', 'trace_artifacts', ['trace_id'], unique=False)
    op.create_table('upload_sessions',
    sa.Column('upload_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expected_size', sa.Integer(), nullable=True),
    sa.Column('expected_sha256', sa.String(length=128), nullable=True),
    sa.Column('received_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_chunk_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.create_table('workbench_agent_review_projection',
    sa.Column('finding_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('ticket_id', sa.String(length=64), nullable=False),
    sa.Column('doc_id', sa.String(length=128), nullable=True),
    sa.Column('source_file_id', sa.String(length=64), nullable=True),
    sa.Column('parse_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('evidence_id', sa.String(length=128), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('problem_summary', sa.String(length=1024), nullable=True),
    sa.Column('problem_detail', sa.Text(), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('chunk_quote', sa.Text(), nullable=True),
    sa.Column('page_from', sa.Integer(), nullable=True),
    sa.Column('page_to', sa.Integer(), nullable=True),
    sa.Column('source_anchor_json', sa.JSON(), nullable=True),
    sa.Column('why_wrong', sa.Text(), nullable=True),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('suggested_operation', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('projection_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_index('ix_warp_doc', 'workbench_agent_review_projection', ['tenant_id', 'doc_id'], unique=False)
    op.create_index('ix_warp_severity', 'workbench_agent_review_projection', ['tenant_id', 'severity'], unique=False)
    op.create_index('ix_warp_ticket', 'workbench_agent_review_projection', ['tenant_id', 'ticket_id'], unique=False)
    op.create_table('workbench_chunk_edits',
    sa.Column('chunk_edit_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('source_file_id', sa.String(length=64), nullable=False),
    sa.Column('parse_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('base_evidence_id', sa.String(length=128), nullable=False),
    sa.Column('edit_scope', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('vector_text', sa.Text(), nullable=True),
    sa.Column('section_path', sa.JSON(), nullable=True),
    sa.Column('metadata_patch', sa.JSON(), nullable=True),
    sa.Column('citation_payload', sa.JSON(), nullable=True),
    sa.Column('source_block_ids', sa.JSON(), nullable=True),
    sa.Column('edit_reason', sa.String(length=2048), nullable=True),
    sa.Column('edited_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('downstream_revision_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('chunk_edit_id')
    )
    op.create_index('ix_wb_chunk_edits_editor', 'workbench_chunk_edits', ['edited_by'], unique=False)
    op.create_index('ix_wb_chunk_edits_evidence', 'workbench_chunk_edits', ['base_evidence_id'], unique=False)
    op.create_index('ix_wb_chunk_edits_snapshot', 'workbench_chunk_edits', ['parse_snapshot_id'], unique=False)
    op.create_index('ix_wb_chunk_edits_source', 'workbench_chunk_edits', ['source_file_id'], unique=False)
    op.create_table('workbench_chunk_projection',
    sa.Column('evidence_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('doc_id', sa.String(length=128), nullable=False),
    sa.Column('source_file_id', sa.String(length=64), nullable=True),
    sa.Column('parse_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('chunk_ordinal', sa.Integer(), nullable=False),
    sa.Column('content_preview', sa.String(length=512), nullable=True),
    sa.Column('section_path_json', sa.JSON(), nullable=True),
    sa.Column('page_from', sa.Integer(), nullable=True),
    sa.Column('page_to', sa.Integer(), nullable=True),
    sa.Column('source_anchor_json', sa.JSON(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('active_revision_id', sa.String(length=64), nullable=True),
    sa.Column('projection_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index('ix_wcp_doc', 'workbench_chunk_projection', ['tenant_id', 'doc_id', 'chunk_ordinal'], unique=False)
    op.create_index('ix_wcp_snapshot', 'workbench_chunk_projection', ['parse_snapshot_id'], unique=False)
    op.create_index('ix_wcp_state', 'workbench_chunk_projection', ['tenant_id', 'state'], unique=False)
    op.create_table('workbench_document_projection',
    sa.Column('doc_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('source_file_id', sa.String(length=64), nullable=True),
    sa.Column('parse_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('published_doc_id', sa.String(length=64), nullable=True),
    sa.Column('upload_id', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('document_state', sa.String(length=32), nullable=True),
    sa.Column('publish_state', sa.String(length=32), nullable=True),
    sa.Column('active_index_version', sa.String(length=64), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('parser_profile_id', sa.String(length=128), nullable=True),
    sa.Column('parser_profile_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('projection_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('degraded_reason', sa.String(length=512), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index('ix_wdp_list', 'workbench_document_projection', ['tenant_id', 'collection_id', 'projection_updated_at'], unique=False)
    op.create_index('ix_wdp_stale', 'workbench_document_projection', ['is_stale', 'projection_updated_at'], unique=False)
    op.create_index('ix_wdp_state', 'workbench_document_projection', ['tenant_id', 'collection_id', 'document_state', 'projection_updated_at'], unique=False)
    op.create_table('workbench_projection_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.String(length=128), nullable=False),
    sa.Column('aggregate_version', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_proj_events_aggregate', 'workbench_projection_events', ['aggregate_type', 'aggregate_id', 'aggregate_version'], unique=False)
    op.create_index('ix_proj_events_occurred', 'workbench_projection_events', ['occurred_at'], unique=False)
    op.create_index('ix_proj_events_trace', 'workbench_projection_events', ['trace_id'], unique=False)
    op.create_table('workbench_projection_reconcile_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('collection_id', sa.String(length=64), nullable=True),
    sa.Column('aggregate_type', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scanned_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('degraded_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('ix_wprr_started', 'workbench_projection_reconcile_runs', ['started_at'], unique=False)
    op.create_index('ix_wprr_status', 'workbench_projection_reconcile_runs', ['status'], unique=False)
    op.create_table('workbench_query_runs',
    sa.Column('query_run_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('token_budget', sa.Integer(), nullable=False),
    sa.Column('request_json', sa.JSON(), nullable=True),
    sa.Column('access_response_json', sa.JSON(), nullable=True),
    sa.Column('knowledge_context_json', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('query_run_id')
    )
    op.create_index('ix_wqr_collection', 'workbench_query_runs', ['tenant_id', 'collection_id', 'created_at'], unique=False)
    op.create_index('ix_wqr_status', 'workbench_query_runs', ['status'], unique=False)
    op.create_index('ix_wqr_user', 'workbench_query_runs', ['tenant_id', 'user_id', 'created_at'], unique=False)
    op.create_table('workbench_task_projection',
    sa.Column('projection_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('upload_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.String(length=64), nullable=True),
    sa.Column('intake_job_id', sa.String(length=64), nullable=True),
    sa.Column('parse_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('ticket_id', sa.String(length=64), nullable=True),
    sa.Column('published_doc_id', sa.String(length=64), nullable=True),
    sa.Column('doc_id', sa.String(length=128), nullable=True),
    sa.Column('source_file_state', sa.String(length=32), nullable=True),
    sa.Column('intake_job_state', sa.String(length=32), nullable=True),
    sa.Column('parse_snapshot_state', sa.String(length=32), nullable=True),
    sa.Column('ticket_state', sa.String(length=32), nullable=True),
    sa.Column('agent_review_state', sa.String(length=32), nullable=True),
    sa.Column('published_document_state', sa.String(length=32), nullable=True),
    sa.Column('index_build_state', sa.String(length=32), nullable=True),
    sa.Column('active_index_version', sa.String(length=64), nullable=True),
    sa.Column('overall_status', sa.String(length=32), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('blocking_reason', sa.String(length=2048), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('projection_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stale_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('degraded_reason', sa.String(length=512), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('projection_id'),
    sa.UniqueConstraint('upload_id')
    )
    op.create_index('ix_wtp_stale', 'workbench_task_projection', ['is_stale', 'stale_after'], unique=False)
    op.create_index('ix_wtp_status', 'workbench_task_projection', ['tenant_id', 'collection_id', 'overall_status', 'projection_updated_at'], unique=False)
    op.create_index('ix_wtp_ticket', 'workbench_task_projection', ['tenant_id', 'ticket_id'], unique=False)
    op.create_index('ix_wtp_user_list', 'workbench_task_projection', ['tenant_id', 'user_id', 'collection_id', 'projection_updated_at'], unique=False)
    op.create_table('workbench_ticket_projection',
    sa.Column('ticket_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('upload_id', sa.String(length=64), nullable=True),
    sa.Column('source_file_id', sa.String(length=64), nullable=True),
    sa.Column('parse_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('doc_id', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=True),
    sa.Column('routing_recommendation', sa.String(length=32), nullable=True),
    sa.Column('assignee_user_id', sa.String(length=128), nullable=True),
    sa.Column('agent_decision', sa.String(length=32), nullable=True),
    sa.Column('agent_risk_level', sa.String(length=32), nullable=True),
    sa.Column('agent_finding_count', sa.Integer(), nullable=False),
    sa.Column('agent_blocking_finding_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('projection_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('degraded_reason', sa.String(length=512), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index('ix_wtkp_list', 'workbench_ticket_projection', ['tenant_id', 'collection_id', 'projection_updated_at'], unique=False)
    op.create_index('ix_wtkp_stale', 'workbench_ticket_projection', ['is_stale', 'projection_updated_at'], unique=False)
    op.create_index('ix_wtkp_state', 'workbench_ticket_projection', ['tenant_id', 'collection_id', 'state', 'projection_updated_at'], unique=False)
    op.create_table('workbench_upload_sessions',
    sa.Column('upload_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('source_file_id', sa.String(length=64), nullable=True),
    sa.Column('intake_job_id', sa.String(length=64), nullable=True),
    sa.Column('parse_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('ticket_id', sa.String(length=64), nullable=True),
    sa.Column('selected_parser_profile_id', sa.String(length=128), nullable=True),
    sa.Column('parser_override_json', sa.JSON(), nullable=True),
    sa.Column('access_scope_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.create_index('ix_wb_uploads_collection', 'workbench_upload_sessions', ['collection_id'], unique=False)
    op.create_index('ix_wb_uploads_status', 'workbench_upload_sessions', ['status'], unique=False)
    op.create_index('ix_wb_uploads_tenant', 'workbench_upload_sessions', ['tenant_id'], unique=False)
    op.create_index('ix_wb_uploads_user', 'workbench_upload_sessions', ['user_id'], unique=False)
    op.create_table('workbench_user_preferences',
    sa.Column('preference_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('preference_type', sa.String(length=64), nullable=False),
    sa.Column('preference_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('preference_id')
    )
    op.create_index('ix_wb_prefs_type', 'workbench_user_preferences', ['user_id', 'preference_type'], unique=False)
    op.create_index('ix_wb_prefs_user', 'workbench_user_preferences', ['user_id'], unique=False)
    op.create_table('admin_sessions',
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('api_key_registry',
    sa.Column('api_key_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('agent_type_id', sa.String(length=128), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('knowledge_scopes', sa.JSON(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('debug_permission', sa.Boolean(), nullable=False),
    sa.Column('max_context_tokens', sa.Integer(), nullable=False),
    sa.Column('token_budget_limit', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('api_key_id')
    )
    op.create_index('ix_api_key_registry_state', 'api_key_registry', ['state'], unique=False)
    op.create_index('ix_api_key_registry_tenant', 'api_key_registry', ['tenant_id'], unique=False)
    op.create_table('application_profiles',
    sa.Column('application_profile_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('allowed_collections', sa.JSON(), nullable=True),
    sa.Column('default_collections', sa.JSON(), nullable=True),
    sa.Column('allow_cross_collection', sa.Boolean(), nullable=True),
    sa.Column('default_token_budget', sa.Integer(), nullable=True),
    sa.Column('default_budget_policy', sa.String(length=32), nullable=True),
    sa.Column('metadata_policy', sa.String(length=32), nullable=True),
    sa.Column('debug_permission', sa.Boolean(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('application_profile_id')
    )
    op.create_table('approval_audit_log',
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('ticket_id', sa.String(length=64), nullable=False),
    sa.Column('intake_job_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('before_state', sa.String(length=32), nullable=True),
    sa.Column('after_state', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.String(length=2048), nullable=True),
    sa.Column('payload_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['approval_tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('collections',
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('authority_level', sa.Integer(), nullable=True),
    sa.Column('access_policy', sa.JSON(), nullable=True),
    sa.Column('default_parser_profile_id', sa.String(length=64), nullable=False),
    sa.Column('default_retrieval_profile_id', sa.String(length=64), nullable=False),
    sa.Column('default_approval_policy_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('collection_id')
    )
    op.create_table('principal_profiles',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('role_ids', sa.JSON(), nullable=True),
    sa.Column('group_ids', sa.JSON(), nullable=True),
    sa.Column('department_ids', sa.JSON(), nullable=True),
    sa.Column('clearance_level', sa.Integer(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('publish_jobs',
    sa.Column('publish_id', sa.String(length=64), nullable=False),
    sa.Column('intake_job_id', sa.String(length=64), nullable=False),
    sa.Column('final_doc_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('asset_paths', sa.JSON(), nullable=True),
    sa.Column('index_build_job_id', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['intake_job_id'], ['intake_jobs.intake_job_id'], ),
    sa.PrimaryKeyConstraint('publish_id')
    )
    op.create_table('stage_tasks',
    sa.Column('stage_task_id', sa.String(length=64), nullable=False),
    sa.Column('intake_job_id', sa.String(length=64), nullable=False),
    sa.Column('stage_name', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('input_hash', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('rerun_round', sa.Integer(), nullable=False),
    sa.Column('rerun_reason_code', sa.String(length=64), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['intake_job_id'], ['intake_jobs.intake_job_id'], ),
    sa.PrimaryKeyConstraint('stage_task_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_stage_tasks_intake_job_id', 'stage_tasks', ['intake_job_id'], unique=False)
    op.create_table('collection_profile_bindings',
    sa.Column('binding_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('parser_profile_id', sa.String(length=128), nullable=False),
    sa.Column('retrieval_profile_id', sa.String(length=128), nullable=False),
    sa.Column('approval_policy_id', sa.String(length=128), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('binding_version', sa.Integer(), nullable=False),
    sa.Column('config_hash', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('binding_id')
    )
    op.create_index('ix_bindings_collection_version', 'collection_profile_bindings', ['collection_id', 'binding_version'], unique=False)
    op.create_table('documents',
    sa.Column('doc_id', sa.String(length=128), nullable=False),
    sa.Column('logical_document_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('source_hash', sa.String(length=128), nullable=False),
    sa.Column('source_content_hash', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('publish_status', sa.String(length=32), nullable=True),
    sa.Column('index_status', sa.String(length=32), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authority_level', sa.Integer(), nullable=True),
    sa.Column('governance_level', sa.String(length=32), nullable=True),
    sa.Column('access_policy', sa.String(length=64), nullable=True),
    sa.Column('domain_tags', sa.JSON(), nullable=True),
    sa.Column('risk_tags', sa.JSON(), nullable=True),
    sa.Column('quality_summary', sa.String(length=2048), nullable=True),
    sa.Column('processing_summary', sa.String(length=2048), nullable=True),
    sa.Column('asset_paths', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index('ix_documents_collection_archived', 'documents', ['collection_id', 'archived'], unique=False)
    op.create_table('index_build_jobs',
    sa.Column('index_build_job_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('target_index_version', sa.String(length=64), nullable=False),
    sa.Column('publish_id', sa.String(length=64), nullable=True),
    sa.Column('reindex_job_id', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('embedding_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['publish_id'], ['publish_jobs.publish_id'], ),
    sa.ForeignKeyConstraint(['reindex_job_id'], ['reindex_jobs.reindex_job_id'], ),
    sa.PrimaryKeyConstraint('index_build_job_id')
    )
    op.create_index('ix_index_build_jobs_collection', 'index_build_jobs', ['collection_id'], unique=False)
    op.create_table('published_documents',
    sa.Column('published_document_id', sa.String(length=64), nullable=False),
    sa.Column('final_doc_id', sa.String(length=128), nullable=False),
    sa.Column('logical_document_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_content_hash', sa.String(length=128), nullable=False),
    sa.Column('canonical_hash', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('active_index_version', sa.String(length=64), nullable=False),
    sa.Column('previous_state', sa.String(length=32), nullable=True),
    sa.Column('supersedes_final_doc_id', sa.String(length=128), nullable=True),
    sa.Column('created_by_ticket_id', sa.String(length=64), nullable=True),
    sa.Column('asset_paths', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('published_document_id'),
    sa.UniqueConstraint('final_doc_id')
    )
    op.create_index('ix_published_docs_collection_id', 'published_documents', ['collection_id'], unique=False)
    op.create_index('ix_published_docs_logical_id', 'published_documents', ['logical_document_id'], unique=False)
    op.create_index('ix_published_docs_source_hash', 'published_documents', ['source_content_hash'], unique=False)
    op.create_table('source_files',
    sa.Column('source_file_id', sa.String(length=64), nullable=False),
    sa.Column('upload_id', sa.String(length=64), nullable=True),
    sa.Column('object_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('original_name', sa.String(length=512), nullable=False),
    sa.Column('sanitized_name', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('claimed_by_job_id', sa.String(length=64), nullable=True),
    sa.Column('scan_result_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['object_blobs.object_id'], ),
    sa.ForeignKeyConstraint(['scan_result_id'], ['malware_scan_results.scan_result_id'], use_alter=True),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_sessions.upload_id'], ),
    sa.PrimaryKeyConstraint('source_file_id'),
    sa.UniqueConstraint('claimed_by_job_id')
    )
    op.create_index('ix_source_files_active_unique', 'source_files', ['content_hash', 'collection_id'], unique=True, postgresql_where=sa.text("state IN ('uploading', 'uploaded', 'scanning', 'ready', 'claimed', 'consumed')"))
    op.create_index('ix_source_files_collection_state', 'source_files', ['collection_id', 'state'], unique=False)
    op.create_index('ix_source_files_content_hash_collection', 'source_files', ['content_hash', 'collection_id'], unique=False)
    op.create_index('ix_source_files_object_id', 'source_files', ['object_id'], unique=False)
    op.create_index('ix_source_files_upload_id', 'source_files', ['upload_id'], unique=False)
    op.create_table('stage_attempts',
    sa.Column('stage_attempt_id', sa.String(length=64), nullable=False),
    sa.Column('stage_task_id', sa.String(length=64), nullable=False),
    sa.Column('intake_job_id', sa.String(length=64), nullable=False),
    sa.Column('stage_name', sa.String(length=32), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_summary_hash', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['intake_job_id'], ['intake_jobs.intake_job_id'], ),
    sa.ForeignKeyConstraint(['stage_task_id'], ['stage_tasks.stage_task_id'], ),
    sa.PrimaryKeyConstraint('stage_attempt_id'),
    sa.UniqueConstraint('stage_task_id', 'attempt_no', name='uix_stage_attempt_task_no')
    )
    op.create_table('document_policies',
    sa.Column('policy_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('doc_id', sa.String(length=128), nullable=False),
    sa.Column('effect', sa.String(length=16), nullable=False),
    sa.Column('subjects', sa.JSON(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('policy_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], ),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.doc_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('policy_id'),
    sa.UniqueConstraint('doc_id', 'collection_id', name='uix_doc_policy')
    )
    op.create_table('malware_scan_results',
    sa.Column('scan_result_id', sa.String(length=64), nullable=False),
    sa.Column('source_file_id', sa.String(length=64), nullable=False),
    sa.Column('engine', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('signature', sa.String(length=256), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_result_ref', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.source_file_id'], ),
    sa.PrimaryKeyConstraint('scan_result_id')
    )
    op.create_table('published_document_lifecycle_audit',
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('published_document_id', sa.String(length=64), nullable=False),
    sa.Column('final_doc_id', sa.String(length=128), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('before_state', sa.String(length=32), nullable=True),
    sa.Column('after_state', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.String(length=2048), nullable=True),
    sa.Column('payload_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['published_document_id'], ['published_documents.published_document_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_pub_doc_audit_doc_id', 'published_document_lifecycle_audit', ['published_document_id'], unique=False)
    op.create_table('stage_results',
    sa.Column('stage_result_id', sa.String(length=64), nullable=False),
    sa.Column('stage_task_id', sa.String(length=64), nullable=False),
    sa.Column('stage_attempt_id', sa.String(length=64), nullable=False),
    sa.Column('intake_job_id', sa.String(length=64), nullable=False),
    sa.Column('stage_name', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('result_hash', sa.String(length=128), nullable=False),
    sa.Column('result_ref', sa.String(length=1024), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['intake_job_id'], ['intake_jobs.intake_job_id'], ),
    sa.ForeignKeyConstraint(['stage_attempt_id'], ['stage_attempts.stage_attempt_id'], ),
    sa.ForeignKeyConstraint(['stage_task_id'], ['stage_tasks.stage_task_id'], ),
    sa.PrimaryKeyConstraint('stage_result_id'),
    sa.UniqueConstraint('stage_task_id')
    )
    # Java service projection tables (not mirrored by SQLAlchemy models)
    op.create_table('api_key_projection',
        sa.Column('api_key_id', sa.String(length=128), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False),
        sa.Column('agent_type_id', sa.String(length=128), nullable=False),
        sa.Column('knowledge_scopes', sa.String(length=2048), nullable=True),
        sa.Column('roles', sa.String(length=2048), nullable=True),
        sa.Column('debug_permission', sa.Boolean(), nullable=False),
        sa.Column('token_budget_limit', sa.Integer(), nullable=False),
        sa.Column('state', sa.String(length=32), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('projection_version', sa.Integer(), nullable=False),
        sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('runtime_synced', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('api_key_id')
    )
    op.create_table('api_key_projection_idempotency',
        sa.Column('idempotency_key', sa.String(length=256), nullable=False),
        sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_table('index_projection_idempotency',
        sa.Column('idempotency_key', sa.String(length=512), nullable=False),
        sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index_projection_idempotency')
    op.drop_table('api_key_projection_idempotency')
    op.drop_table('api_key_projection')
    op.drop_table('stage_results')
    op.drop_index('ix_pub_doc_audit_doc_id', table_name='published_document_lifecycle_audit')
    op.drop_table('published_document_lifecycle_audit')
    op.drop_table('malware_scan_results')
    op.drop_table('document_policies')
    op.drop_table('stage_attempts')
    op.drop_index('ix_source_files_upload_id', table_name='source_files')
    op.drop_index('ix_source_files_object_id', table_name='source_files')
    op.drop_index('ix_source_files_content_hash_collection', table_name='source_files')
    op.drop_index('ix_source_files_collection_state', table_name='source_files')
    op.drop_index('ix_source_files_active_unique', table_name='source_files', postgresql_where=sa.text("state IN ('uploading', 'uploaded', 'scanning', 'ready', 'claimed', 'consumed')"))
    op.drop_table('source_files')
    op.drop_index('ix_published_docs_source_hash', table_name='published_documents')
    op.drop_index('ix_published_docs_logical_id', table_name='published_documents')
    op.drop_index('ix_published_docs_collection_id', table_name='published_documents')
    op.drop_table('published_documents')
    op.drop_index('ix_index_build_jobs_collection', table_name='index_build_jobs')
    op.drop_table('index_build_jobs')
    op.drop_index('ix_documents_collection_archived', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_bindings_collection_version', table_name='collection_profile_bindings')
    op.drop_table('collection_profile_bindings')
    op.drop_index('ix_stage_tasks_intake_job_id', table_name='stage_tasks')
    op.drop_table('stage_tasks')
    op.drop_table('publish_jobs')
    op.drop_table('principal_profiles')
    op.drop_table('collections')
    op.drop_table('approval_audit_log')
    op.drop_table('application_profiles')
    op.drop_index('ix_api_key_registry_tenant', table_name='api_key_registry')
    op.drop_index('ix_api_key_registry_state', table_name='api_key_registry')
    op.drop_table('api_key_registry')
    op.drop_table('admin_sessions')
    op.drop_index('ix_wb_prefs_user', table_name='workbench_user_preferences')
    op.drop_index('ix_wb_prefs_type', table_name='workbench_user_preferences')
    op.drop_table('workbench_user_preferences')
    op.drop_index('ix_wb_uploads_user', table_name='workbench_upload_sessions')
    op.drop_index('ix_wb_uploads_tenant', table_name='workbench_upload_sessions')
    op.drop_index('ix_wb_uploads_status', table_name='workbench_upload_sessions')
    op.drop_index('ix_wb_uploads_collection', table_name='workbench_upload_sessions')
    op.drop_table('workbench_upload_sessions')
    op.drop_index('ix_wtkp_state', table_name='workbench_ticket_projection')
    op.drop_index('ix_wtkp_stale', table_name='workbench_ticket_projection')
    op.drop_index('ix_wtkp_list', table_name='workbench_ticket_projection')
    op.drop_table('workbench_ticket_projection')
    op.drop_index('ix_wtp_user_list', table_name='workbench_task_projection')
    op.drop_index('ix_wtp_ticket', table_name='workbench_task_projection')
    op.drop_index('ix_wtp_status', table_name='workbench_task_projection')
    op.drop_index('ix_wtp_stale', table_name='workbench_task_projection')
    op.drop_table('workbench_task_projection')
    op.drop_index('ix_wqr_user', table_name='workbench_query_runs')
    op.drop_index('ix_wqr_status', table_name='workbench_query_runs')
    op.drop_index('ix_wqr_collection', table_name='workbench_query_runs')
    op.drop_table('workbench_query_runs')
    op.drop_index('ix_wprr_status', table_name='workbench_projection_reconcile_runs')
    op.drop_index('ix_wprr_started', table_name='workbench_projection_reconcile_runs')
    op.drop_table('workbench_projection_reconcile_runs')
    op.drop_index('ix_proj_events_trace', table_name='workbench_projection_events')
    op.drop_index('ix_proj_events_occurred', table_name='workbench_projection_events')
    op.drop_index('ix_proj_events_aggregate', table_name='workbench_projection_events')
    op.drop_table('workbench_projection_events')
    op.drop_index('ix_wdp_state', table_name='workbench_document_projection')
    op.drop_index('ix_wdp_stale', table_name='workbench_document_projection')
    op.drop_index('ix_wdp_list', table_name='workbench_document_projection')
    op.drop_table('workbench_document_projection')
    op.drop_index('ix_wcp_state', table_name='workbench_chunk_projection')
    op.drop_index('ix_wcp_snapshot', table_name='workbench_chunk_projection')
    op.drop_index('ix_wcp_doc', table_name='workbench_chunk_projection')
    op.drop_table('workbench_chunk_projection')
    op.drop_index('ix_wb_chunk_edits_source', table_name='workbench_chunk_edits')
    op.drop_index('ix_wb_chunk_edits_snapshot', table_name='workbench_chunk_edits')
    op.drop_index('ix_wb_chunk_edits_evidence', table_name='workbench_chunk_edits')
    op.drop_index('ix_wb_chunk_edits_editor', table_name='workbench_chunk_edits')
    op.drop_table('workbench_chunk_edits')
    op.drop_index('ix_warp_ticket', table_name='workbench_agent_review_projection')
    op.drop_index('ix_warp_severity', table_name='workbench_agent_review_projection')
    op.drop_index('ix_warp_doc', table_name='workbench_agent_review_projection')
    op.drop_table('workbench_agent_review_projection')
    op.drop_table('upload_sessions')
    op.drop_index('ix_trace_artifacts_trace_id', table_name='trace_artifacts')
    op.drop_index('ix_trace_artifacts_kind', table_name='trace_artifacts')
    op.drop_index('ix_trace_artifacts_created_at', table_name='trace_artifacts')
    op.drop_table('trace_artifacts')
    op.drop_table('tenants')
    op.drop_index('ix_telemetry_trace_id', table_name='telemetry_events')
    op.drop_index('ix_telemetry_intake_job', table_name='telemetry_events')
    op.drop_index('ix_telemetry_event_time', table_name='telemetry_events')
    op.drop_index('ix_telemetry_event_name', table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_index('ix_run_traces_trace_id', table_name='run_traces')
    op.drop_index('ix_run_traces_source_file', table_name='run_traces')
    op.drop_index('ix_run_traces_intake_job', table_name='run_traces')
    op.drop_index('ix_run_traces_final_doc', table_name='run_traces')
    op.drop_table('run_traces')
    op.drop_index('ix_run_steps_trace_id', table_name='run_steps')
    op.drop_index('ix_run_steps_created_at', table_name='run_steps')
    op.drop_table('run_steps')
    op.drop_index('ix_review_feedback_review_id', table_name='review_quality_feedback')
    op.drop_index('ix_review_feedback_intake_job', table_name='review_quality_feedback')
    op.drop_table('review_quality_feedback')
    op.drop_table('retrieval_profiles_admin')
    op.drop_index('ix_retrieval_profiles_enabled', table_name='retrieval_profiles')
    op.drop_index('ix_retrieval_profiles_collection', table_name='retrieval_profiles')
    op.drop_table('retrieval_profiles')
    op.drop_table('reindex_jobs')
    op.drop_table('parser_profiles')
    op.drop_index('ix_parse_snapshots_source_file', table_name='parse_snapshots')
    op.drop_index('ix_parse_snapshots_collection', table_name='parse_snapshots')
    op.drop_table('parse_snapshots')
    op.drop_index('ix_outbox_status_next_attempt', table_name='outbox_events')
    op.drop_index('ix_outbox_aggregate', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index('ix_ops_audit_trace', table_name='ops_audit_log')
    op.drop_index('ix_ops_audit_target', table_name='ops_audit_log')
    op.drop_index('ix_ops_audit_idempotency', table_name='ops_audit_log')
    op.drop_index('ix_ops_audit_created', table_name='ops_audit_log')
    op.drop_index('ix_ops_audit_actor', table_name='ops_audit_log')
    op.drop_table('ops_audit_log')
    op.drop_table('object_blobs')
    op.drop_table('llm_cost_daily')
    op.drop_index('ix_llm_call_trace_id', table_name='llm_call_log')
    op.drop_index('ix_llm_call_status', table_name='llm_call_log')
    op.drop_index('ix_llm_call_intake_job', table_name='llm_call_log')
    op.drop_index('ix_llm_call_created', table_name='llm_call_log')
    op.drop_table('llm_call_log')
    op.drop_table('jobs')
    op.drop_table('intake_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index('ix_indexed_docs_collection_version', table_name='indexed_documents')
    op.drop_table('indexed_documents')
    op.drop_index('ix_index_versions_status', table_name='index_versions')
    op.drop_index('ix_index_versions_collection', table_name='index_versions')
    op.drop_table('index_versions')
    op.drop_table('index_registry')
    op.drop_index('ix_consumer_idempotency_pk', table_name='consumer_idempotency')
    op.drop_index('ix_consumer_idempotency_key', table_name='consumer_idempotency')
    op.drop_table('consumer_idempotency')
    op.drop_index('ix_chunk_registry_tenant_collection', table_name='chunk_registry')
    op.drop_index('ix_chunk_registry_final_doc_version', table_name='chunk_registry')
    op.drop_index('ix_chunk_registry_collection_version', table_name='chunk_registry')
    op.drop_table('chunk_registry')
    op.drop_table('approval_tickets')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
