-- Auto-generated schema for Java retrieval service tests.

-- Source of truth: SQLAlchemy models in packages/persistence/src/reality_rag_persistence/models.py

-- and hardcoded DDL for Java-only projection tables.

-- Regenerate with: uv run python scripts/generate_java_test_schema.py


-- index_projection_idempotency
CREATE TABLE IF NOT EXISTS index_projection_idempotency (
    idempotency_key VARCHAR(512) PRIMARY KEY,
    processed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- run_traces
CREATE TABLE IF NOT EXISTS run_traces (
    run_trace_id VARCHAR(128) NOT NULL PRIMARY KEY,
    trace_id VARCHAR(64) NOT NULL,
    run_kind VARCHAR(64) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    collection_id VARCHAR(64) NOT NULL,
    principal_id VARCHAR(128) NOT NULL,
    query_id VARCHAR(128) NOT NULL,
    index_version_id VARCHAR(64) NOT NULL,
    profile_id VARCHAR(64) NOT NULL,
    root_status VARCHAR(32) NOT NULL,
    debug_ref VARCHAR(1024) NOT NULL,
    result_count INTEGER NOT NULL DEFAULT 0,
    source_file_id VARCHAR(64),
    intake_job_id VARCHAR(64),
    final_doc_id VARCHAR(128),
    approval_ticket_id VARCHAR(64),
    extra_json TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);


-- run_steps
CREATE TABLE IF NOT EXISTS run_steps (
    run_step_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(64) NOT NULL,
    step_name VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    summary VARCHAR(4096) NOT NULL,
    details_json TEXT,
    created_at TIMESTAMP
);


-- index_versions
CREATE TABLE IF NOT EXISTS index_versions (
    index_version_id VARCHAR(64) NOT NULL PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    collection_id VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'building',
    schema_version VARCHAR(32) NOT NULL,
    index_profile_id VARCHAR(64) NOT NULL,
    chunk_profile_id VARCHAR(64) NOT NULL,
    embedding_model VARCHAR(128) NOT NULL,
    opensearch_index VARCHAR(128) NOT NULL,
    qdrant_collection VARCHAR(128) NOT NULL,
    chunk_count INTEGER NOT NULL DEFAULT 0,
    previous_active_index_version_id VARCHAR(64),
    replaced_by_index_version_id VARCHAR(64),
    created_at TIMESTAMP,
    activated_at TIMESTAMP,
    rolled_back_at TIMESTAMP,
    cleaned_up_at TIMESTAMP,
    updated_at TIMESTAMP
);


-- index_registry
CREATE TABLE IF NOT EXISTS index_registry (
    collection_id VARCHAR(64) NOT NULL PRIMARY KEY,
    index_version VARCHAR(64) NOT NULL,
    previous_index_version VARCHAR(64),
    target_index_version VARCHAR(64),
    status VARCHAR(32) DEFAULT 'indexed',
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);


-- published_documents
CREATE TABLE IF NOT EXISTS published_documents (
    published_document_id VARCHAR(64) NOT NULL PRIMARY KEY,
    final_doc_id VARCHAR(128) NOT NULL,
    logical_document_id VARCHAR(128) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    collection_id VARCHAR(64) NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    source_content_hash VARCHAR(128) NOT NULL,
    canonical_hash VARCHAR(128) NOT NULL,
    state VARCHAR(32) NOT NULL DEFAULT 'published',
    active_index_version VARCHAR(64) NOT NULL,
    previous_state VARCHAR(32),
    supersedes_final_doc_id VARCHAR(128),
    created_by_ticket_id VARCHAR(64),
    asset_paths TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);


-- chunk_registry
CREATE TABLE IF NOT EXISTS chunk_registry (
    chunk_id VARCHAR(128) NOT NULL PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    collection_id VARCHAR(64) NOT NULL,
    final_doc_id VARCHAR(128) NOT NULL,
    index_version_id VARCHAR(64) NOT NULL,
    available_int INTEGER NOT NULL DEFAULT 1,
    visibility VARCHAR(32) NOT NULL DEFAULT 'internal',
    payload_json TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);


-- retrieval_profiles
CREATE TABLE IF NOT EXISTS retrieval_profiles (
    profile_id VARCHAR(64) NOT NULL,
    collection_id VARCHAR(64) NOT NULL,
    profile_version INTEGER NOT NULL DEFAULT 1,
    profile_hash VARCHAR(128) NOT NULL,
    bm25_weight DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    vector_weight DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    candidate_top_k INTEGER NOT NULL DEFAULT 20,
    similarity_threshold DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    rerank_enabled BOOLEAN NOT NULL DEFAULT true,
    rerank_model VARCHAR(128) NOT NULL,
    fail_policy VARCHAR(32) NOT NULL DEFAULT 'fail_closed',
    expansion_policy TEXT,
    pack_budget INTEGER NOT NULL DEFAULT 1200,
    enabled BOOLEAN NOT NULL DEFAULT true,
    updated_at TIMESTAMP,
    updated_by VARCHAR(128) NOT NULL DEFAULT 'system',
    PRIMARY KEY (profile_id, collection_id)
);


-- indexed_documents
CREATE TABLE IF NOT EXISTS indexed_documents (
    indexed_document_id VARCHAR(256) NOT NULL PRIMARY KEY,
    final_doc_id VARCHAR(128) NOT NULL,
    collection_id VARCHAR(64) NOT NULL,
    index_version VARCHAR(64) NOT NULL,
    parser_id VARCHAR(64) NOT NULL,
    source_suffix VARCHAR(32) NOT NULL,
    chunk_count INTEGER NOT NULL DEFAULT 0,
    embedding_count INTEGER NOT NULL DEFAULT 0,
    visible_chunk_count INTEGER NOT NULL DEFAULT 0,
    hidden_chunk_count INTEGER NOT NULL DEFAULT 0,
    has_toc_chunk BOOLEAN NOT NULL DEFAULT false,
    has_parent_chunk BOOLEAN NOT NULL DEFAULT false,
    document_metadata TEXT,
    outline TEXT,
    state VARCHAR(32) NOT NULL DEFAULT 'candidate',
    activated_at TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);
