-- Smoke-test schema for retrieval service.
-- This schema describes the tables expected at runtime.
-- With spring.sql.init.mode=never in application-smoke.yaml, these tables
-- are NOT auto-created by Spring. In production-like smoke runs, tables are
-- managed by the database migration or auto-DDL mechanism of the actual
-- JDBC driver (PostgreSQL). This file is kept as a reference DDL only.

CREATE TABLE IF NOT EXISTS retrieval_profiles (
    profile_id VARCHAR(64) NOT NULL,
    collection_id VARCHAR(64) NOT NULL,
    profile_version INTEGER NOT NULL,
    profile_hash VARCHAR(128) NOT NULL,
    bm25_weight DOUBLE PRECISION NOT NULL,
    vector_weight DOUBLE PRECISION NOT NULL,
    candidate_top_k INTEGER NOT NULL,
    similarity_threshold DOUBLE PRECISION NOT NULL,
    rerank_enabled BOOLEAN NOT NULL,
    rerank_model VARCHAR(128) NOT NULL,
    fail_policy VARCHAR(32) NOT NULL,
    expansion_policy TEXT,
    pack_budget INTEGER NOT NULL,
    enabled BOOLEAN NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR(128) NOT NULL,
    PRIMARY KEY (profile_id, collection_id)
);

CREATE TABLE IF NOT EXISTS run_traces (
    run_trace_id VARCHAR(128) PRIMARY KEY,
    trace_id VARCHAR(64) NOT NULL,
    run_kind VARCHAR(64) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    collection_id VARCHAR(64) NOT NULL,
    principal_id VARCHAR(128) NOT NULL,
    query_id VARCHAR(128) NOT NULL,
    index_version_id VARCHAR(64) NOT NULL,
    profile_id VARCHAR(64) NOT NULL,
    root_status VARCHAR(32) NOT NULL,
    debug_ref VARCHAR(1024) NOT NULL,
    result_count INTEGER NOT NULL,
    source_file_id VARCHAR(64),
    intake_job_id VARCHAR(64),
    final_doc_id VARCHAR(128),
    approval_ticket_id VARCHAR(64),
    extra_json JSON,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS run_steps (
    run_step_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(64) NOT NULL,
    step_name VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    summary VARCHAR(4096) NOT NULL,
    details_json JSON,
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS published_documents (
    published_document_id VARCHAR(64) PRIMARY KEY,
    final_doc_id VARCHAR(128) NOT NULL,
    logical_document_id VARCHAR(128) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    collection_id VARCHAR(64) NOT NULL,
    version INTEGER NOT NULL,
    source_content_hash VARCHAR(128) NOT NULL,
    canonical_hash VARCHAR(128) NOT NULL,
    state VARCHAR(32) NOT NULL,
    active_index_version VARCHAR(64) NOT NULL,
    previous_state VARCHAR(32),
    supersedes_final_doc_id VARCHAR(128),
    created_by_ticket_id VARCHAR(64),
    asset_paths TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS index_registry (
    collection_id VARCHAR(64) PRIMARY KEY,
    index_version VARCHAR(64) NOT NULL,
    previous_index_version VARCHAR(64),
    target_index_version VARCHAR(64),
    status VARCHAR(32),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS index_versions (
    index_version_id VARCHAR(64) PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    collection_id VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    schema_version VARCHAR(32) NOT NULL,
    index_profile_id VARCHAR(64) NOT NULL,
    chunk_profile_id VARCHAR(64) NOT NULL,
    embedding_model VARCHAR(128) NOT NULL,
    opensearch_index VARCHAR(128) NOT NULL,
    qdrant_collection VARCHAR(128) NOT NULL,
    chunk_count INTEGER NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chunk_registry (
    chunk_id VARCHAR(128) PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    collection_id VARCHAR(64) NOT NULL,
    final_doc_id VARCHAR(128) NOT NULL,
    index_version_id VARCHAR(64) NOT NULL,
    available_int INTEGER NOT NULL,
    visibility VARCHAR(32) NOT NULL,
    payload_json JSON,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS indexed_documents (
    indexed_document_id VARCHAR(64) PRIMARY KEY,
    final_doc_id VARCHAR(128) NOT NULL,
    collection_id VARCHAR(64) NOT NULL,
    index_version VARCHAR(64) NOT NULL,
    parser_id VARCHAR(64) NOT NULL,
    source_suffix VARCHAR(32) NOT NULL,
    chunk_count INTEGER NOT NULL,
    embedding_count INTEGER NOT NULL,
    visible_chunk_count INTEGER NOT NULL,
    hidden_chunk_count INTEGER NOT NULL,
    has_toc_chunk BOOLEAN NOT NULL,
    has_parent_chunk BOOLEAN NOT NULL,
    document_metadata TEXT,
    outline TEXT,
    state VARCHAR(32) NOT NULL,
    activated_at TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);
